### PR TITLE
posix: port to Windows, part 5

### PR DESCRIPTION
**Pull request by mslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/97)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[include/libpmemfile-posix.h.in, line 204 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/97#-KhS0ZyeDNg8_rcwS0zf:-KhS0ZyfJroGLLh_o0CQ:b-kkr0e8) ([raw file](https://github.com/pmem/pmemfile/blob/013fae7e5d4ea1367a127b136f02846bba1ae19b/include/libpmemfile-posix.h.in#L204)):*
> ```
> typedef uint32_t pmemfile_gid_t;
> typedef int64_t pmemfile_ssize_t;
> typedef int64_t pmemfile_off_t;
> ```

Why not to always define it as int64_t?
Why not to always act as NATIVE_TYPES is 0?

---

*[src/libpmemfile-posix/os_thread_windows.c, line 86 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/97#-KhS1szeH4U0uzLGY-Na:-KhS1szeH4U0uzLGY-Nb:ba4j992) ([raw file](https://github.com/pmem/pmemfile/blob/013fae7e5d4ea1367a127b136f02846bba1ae19b/src/libpmemfile-posix/os_thread_windows.c#L86)):*
> ```C
> {
> 	COMPILE_ERROR_ON(sizeof(os_rwlock_t) < sizeof(win_rwlock_t));
> 	win_rwlock_t *rw = (win_rwlock_t *)m;
> ```

how can it work if os_rwlock_t is smaller than win_rwlock_t?

---

*[src/libpmemfile-posix/os_thread_windows.c, line 155 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/97#-KhS2BL9GMZLJNUdwdw_:-KhS2BL9GMZLJNUdwdwa:b-bsd4w3) ([raw file](https://github.com/pmem/pmemfile/blob/013fae7e5d4ea1367a127b136f02846bba1ae19b/src/libpmemfile-posix/os_thread_windows.c#L155)):*
> ```C
> 	COMPILE_ERROR_ON(sizeof(*once) < sizeof(long));
> 
> 	// XXX this implementation doesn't wait for init_routine to complete
> ```

C++ comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Comment by marcinslusarz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[include/libpmemfile-posix.h.in, line 204 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/97#-KhS0ZyeDNg8_rcwS0zf:-KhS3oyhTR00dSWiO63d:bg8gk6v) ([raw file](https://github.com/pmem/pmemfile/blob/013fae7e5d4ea1367a127b136f02846bba1ae19b/include/libpmemfile-posix.h.in#L204)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

Why not to always define it as int64_t?
Why not to always act as NATIVE_TYPES is 0?
</blockquote></details>

I wanted to do it this way, but was outvoted by @GBuella and @sarahhelinek. I'll let them explain that.

---

*[src/libpmemfile-posix/os_thread_windows.c, line 86 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/97#-KhS1szeH4U0uzLGY-Na:-KhS4e1hhZRNaBogbIDJ:bcf1dgi) ([raw file](https://github.com/pmem/pmemfile/blob/013fae7e5d4ea1367a127b136f02846bba1ae19b/src/libpmemfile-posix/os_thread_windows.c#L86)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

how can it work if os_rwlock_t is smaller than win_rwlock_t?
</blockquote></details>

It can't. That's what COMPILER_ERROR_ON checks for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Comment by mslusarz** [comment]
Review status: 19 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/libpmemfile-posix/os_thread_windows.c, line 155 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/97#-KhS2BL9GMZLJNUdwdw_:-KhTCREPpFPPNHvcsUf1:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/013fae7e5d4ea1367a127b136f02846bba1ae19b/src/libpmemfile-posix/os_thread_windows.c#L155)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

C++ comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libpmemfile-posix/os_thread_windows.c, line 86 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/97#-KhS1szeH4U0uzLGY-Na:-KhTO0tVJk6D2P3THSrI:b-28rle2) ([raw file](https://github.com/pmem/pmemfile/blob/013fae7e5d4ea1367a127b136f02846bba1ae19b/src/libpmemfile-posix/os_thread_windows.c#L86)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

It can't. That's what COMPILER_ERROR_ON checks for.
</blockquote></details>

Oh, my fault. I see COMPILE_ERROR_ON, but think C_ASSERT. ;-) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97#-:-KhTOA_5O4EUtUUrEgtw:bnfp4nl)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/libpmemfile-posix/out.c, line 39 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki59E2CiOpOi401okYK:-Ki59E2CiOpOi401okYL:bal4dt7) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/src/libpmemfile-posix/out.c#L39)):*
> ```C
>  */
> 
> /* alloca is in malloc.h on Windows */
> ```

Why not use VLA?
since we use clang frontend on Windows as well, it should be available.

---

*[tests/posix/pmemfile_test.cpp, line 314 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki59Q-OoZpPQdu68OaT:-Ki59Q-PusLGk3sSTv4P:bi8yn3c) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/tests/posix/pmemfile_test.cpp#L314)):*
> ```cpp
> 	T_OUT("st_ino:     %" PRId64 "\n", st->st_ino);
> 	T_OUT("st_mode:    0%o\n", st->st_mode);
> 	T_OUT("st_nlink:   %" PRIu64 "\n", st->st_nlink);
> ```

Since we don't know for sure what type st_nlink, off_t etc.. are, I suggest casting these while using print format strings, for example:
"%ju", (uintmax_t)st_nlink

I already met clang complaining about e.g. ```long``` vs ```long long``` in format strings.

---

*[tests/posix/dirs/dirs.cpp, line 189 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki5A4Xr4xJDN2L3EkJ0:-Ki5A4XsnRtAlxc5j2CB:b19yvse) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/tests/posix/dirs/dirs.cpp#L189)):*
> ```cpp
> 
> 	for (size_t i = 0; i < 100; ++i) {
> 		sprintf(buf, "/file%04" PRIu64, i);
> ```

"%zu" for size_t

---

*[tests/posix/dirs/dirs.cpp, line 224 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki5A7u3YC9Vf-XN0Wm4:-Ki5A7u3YC9Vf-XN0Wm5:b19yvse) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/tests/posix/dirs/dirs.cpp#L224)):*
> ```cpp
> 
> 	for (size_t i = 0; i < 100; ++i) {
> 		sprintf(buf, "/dir%04" PRIu64, i);
> ```

"%zu" for size_t

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[include/libpmemfile-posix.h.in, line 204 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/97#-KhS0ZyeDNg8_rcwS0zf:-Ki5AE_lLizGX_kcuvrw:bfzv7ls) ([raw file](https://github.com/pmem/pmemfile/blob/013fae7e5d4ea1367a127b136f02846bba1ae19b/include/libpmemfile-posix.h.in#L204)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I wanted to do it this way, but was outvoted by @GBuella and @sarahhelinek. I'll let them explain that.
</blockquote></details>

To make sure we are compatible with off_t, etc. when they are available.
Without triggering any warnings ever.

```
off_t  offset = 7;

pmemfile_lseek(pfp, pfpf, offset, SEEK_END);
lseek(fd, offset, SEEK_END);

pmemfile_off_t other;
other = offset;
offset = other;
// etc...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[include/libpmemfile-posix.h.in, line 204 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/97#-KhS0ZyeDNg8_rcwS0zf:-Ki5BWiegnqtKytzZHHL:b-qgiufy) ([raw file](https://github.com/pmem/pmemfile/blob/013fae7e5d4ea1367a127b136f02846bba1ae19b/include/libpmemfile-posix.h.in#L204)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

To make sure we are compatible with off_t, etc. when they are available.
Without triggering any warnings ever.

```
off_t  offset = 7;

pmemfile_lseek(pfp, pfpf, offset, SEEK_END);
lseek(fd, offset, SEEK_END);

pmemfile_off_t other;
other = offset;
offset = other;
// etc...
```
</blockquote></details>

Notice that the user can also use SEEK_END instead of PMEMFILE_SEEK_END, as long as they don't care about Windows. In the case of PMEMFILE_SEEK_END we just do a compile time assertion on PMEMFILE_SEEK_END == SEEK_END , but I rather prefer this approach. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/libpmemfile-posix/os_thread_windows.c, line 126 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki9h2WEV8A5ZfAZW0ls:-Ki9h2WEV8A5ZfAZW0lt:b-pz7haq) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/src/libpmemfile-posix/os_thread_windows.c#L126)):*
> ```C
> 	COMPILE_ERROR_ON(sizeof(os_tls_key_t) < sizeof(DWORD));
> 
> 	/* XXX - destructor not supported */
> ```

This `os_tls_key_create` seems to be used in `callbacks.c` :
`int ret = os_tls_key_create(&callbacks_key, cb_free);`
and in `out.c` :
`int pth_ret = os_tls_key_create(&Last_errormsg_key, free);`

---

*[src/libpmemfile-posix/os_thread_windows.c, line 155 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki9hkwxgmFerKPu1Gvp:-Ki9hkwxgmFerKPu1Gvq:bcwrh47) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/src/libpmemfile-posix/os_thread_windows.c#L155)):*
> ```C
> 	COMPILE_ERROR_ON(sizeof(*once) < sizeof(long));
> 
> 	/* XXX this implementation doesn't wait for init_routine to complete */
> ```

This `os_once` is used in out.c :
`os_once(&Last_errormsg_key_once, _Last_errormsg_key_alloc);`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/libpmemfile-posix/os_thread_windows.c, line 126 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki9h2WEV8A5ZfAZW0ls:-Ki9i3tSPyuSYBupKYUb:b-jr55so) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/src/libpmemfile-posix/os_thread_windows.c#L126)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

This `os_tls_key_create` seems to be used in `callbacks.c` :
`int ret = os_tls_key_create(&callbacks_key, cb_free);`
and in `out.c` :
`int pth_ret = os_tls_key_create(&Last_errormsg_key, free);`
</blockquote></details>

Notice the destructors used there!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Comment by mslusarz** [comment]
Review status: 6 of 24 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/libpmemfile-posix/os_thread_windows.c, line 126 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki9h2WEV8A5ZfAZW0ls:-KlAPNc1SN5iC-mRabnr:b-mhee32) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/src/libpmemfile-posix/os_thread_windows.c#L126)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Notice the destructors used there!
</blockquote></details>

I know, hence XXX. The same problem exists in NVML. Once someone will fix NVML we can port the fix to pmemfile.

---

*[src/libpmemfile-posix/os_thread_windows.c, line 155 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki9hkwxgmFerKPu1Gvp:-KlAPym_XFi4t0hIOuu6:b-9csb5q) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/src/libpmemfile-posix/os_thread_windows.c#L155)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

This `os_once` is used in out.c :
`os_once(&Last_errormsg_key_once, _Last_errormsg_key_alloc);`
</blockquote></details>

I know :). Again, the same problem exists in NVML. 

---

*[src/libpmemfile-posix/out.c, line 39 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki59E2CiOpOi401okYK:-KlAS34Ncnef4s9Ca1r_:bj7cb4o) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/src/libpmemfile-posix/out.c#L39)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Why not use VLA?
since we use clang frontend on Windows as well, it should be available.
</blockquote></details>

Ok. I'm droppping this patch for now.

---

*[tests/posix/pmemfile_test.cpp, line 314 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki59Q-OoZpPQdu68OaT:-KlAVQDYOlR3EMHdv1uL:b-l7c7j) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/tests/posix/pmemfile_test.cpp#L314)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Since we don't know for sure what type st_nlink, off_t etc.. are, I suggest casting these while using print format strings, for example:
"%ju", (uintmax_t)st_nlink

I already met clang complaining about e.g. ```long``` vs ```long long``` in format strings.
</blockquote></details>

I assume you are talking about MacOSX. I checked how uint64_t is defined there and instead of using Linux or Windows convention "of course" they had to invent a third one. Sigh.

I'll fix it in the next iteration.

---

*[tests/posix/dirs/dirs.cpp, line 189 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki5A4Xr4xJDN2L3EkJ0:-KlAPHuEc7DXI5YKU_Fj:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/tests/posix/dirs/dirs.cpp#L189)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

"%zu" for size_t
</blockquote></details>

Done.

---

*[tests/posix/dirs/dirs.cpp, line 224 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki5A7u3YC9Vf-XN0Wm4:-KlAPJM6ukx-TvhMXVfk:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/tests/posix/dirs/dirs.cpp#L224)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

"%zu" for size_t
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Comment by GBuella** [comment]
Review status: 6 of 25 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[tests/posix/pmemfile_test.cpp, line 314 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/97#-Ki59Q-OoZpPQdu68OaT:-KldSr6VXleBeR3FD5o5:b-ufc5sf) ([raw file](https://github.com/pmem/pmemfile/blob/9570d90612f990901e740aa0f7fefb0179ba770d/tests/posix/pmemfile_test.cpp#L314)):*
<details><summary><i>Previously, mslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I assume you are talking about MacOSX. I checked how uint64_t is defined there and instead of using Linux or Windows convention "of course" they had to invent a third one. Sigh.

I'll fix it in the next iteration.
</blockquote></details>

I don't understand what uint64_t has to do with this in the first place. What?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Comment by krzycz** [comment]
Reviewed 21 of 23 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/97)*

**Pull request closed without merging**
