### PR TITLE
Fix hook_faccessat

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/345)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/345)*

**Comment by GBuella** [comment]
One can read about the difference between pmemfile_vfd_ref and pmemfile_vfd_at_ref :
https://github.com/pmem/pmemfile/blob/master/src/libpmemfile/vfd_table.c#L223

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/345#-:-KtlhXi3RkyC43Fb15ZI:bnfp4nl)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/345#-:-Ktm6-3BdYNefMV3z3zy:bnfp4nl)*

**Pull request merged**
