### PR TITLE
Changed errno in libpmemfile-posix and tests to reflect actual POSIX errno codes

### PR DESCRIPTION
**Pull request by szychows**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/211)

### CODE REVIEW

**Comment by GBuella** [comment]
Perhaps this should be done in a single commit, to make sure all commits in the history can be built (and can be tested)?
I'm not sure how much we managed to keep this invariant so far, but it sounds like something we should strive for.

**Comment by GBuella** [comment]
Otherwise, LGTM

**Comment by sarahjelinek** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/211)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/211#-:-Kn5o9IIRXBhGVb1OZlP:bnfp4nl)*

**Pull request merged**
