### PR TITLE
antool: various minor fixes

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/340)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/340)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[src/tools/antool/listsyscalls.py, line 38 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-Ktm1sLd964RKxIZ6BTa:-Ktm1sLd964RKxIZ6BTb:budedtt) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/listsyscalls.py#L38)):*
> ```Python
> RESULT_UNSUPPORTED_YET = 1
> RESULT_UNSUPPORTED_FLAG = 2
> RESULT_UNSUPPORTED_AT_ALL = 3
> ```

Maybe RESULT_UNSUPPORTED_AT_ALL would be better named as RESULT_NOT_SUPPORTED or simply RESULT_UNSUPPORTED? The 'AT_ALL' seems unnecessary.

---

*[src/tools/antool/syscall.py, line 178 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-Ktm3F_gBSQzcJK5nRnl:-Ktm3F_gBSQzcJK5nRnm:b-5yq8m4) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/syscall.py#L178)):*
> ```Python
>             else:  # pragma: no cover
>                 assert_msg(self.num_str <= 2, "unsupported number of string arguments ({0:d}), "
>                                               "input file can be corrupted".format(self.nstrargs))
> ```

 This message seems strange. Is it intended to reflect that the input file might be corrupted when processing it? If so, perhaps 'input file may be corrupted' is a  better message.

---

*[src/tools/antool/syscall.py, line 191 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-Ktm3VtdWWnFUQwUYW1A:-Ktm3VtdWWnFUQwUYW1B:bj8bld6) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/syscall.py#L191)):*
> ```Python
>             else:  # pragma: no cover
>                 assert_msg(self.num_str <= 3, "unsupported number of string arguments ({0:d}), "
>                                               "input file can be corrupted".format(self.nstrargs))
> ```

same as above.

---

*[src/tools/antool/syscall.py, line 195 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-Ktm3_H51pvvmmXSednJ:-Ktm3_H51pvvmmXSednK:b2nreh6) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/syscall.py#L195)):*
> ```Python
>         else:  # pragma: no cover
>             assert_msg(self.nstrargs <= 3, "unsupported number of string arguments ({0:d}), input file can be corrupted"
>                        .format(self.nstrargs))
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/340)*

**Comment by sarahjelinek** [comment]
Reviewed 2 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/tools/antool/antool.py, line 348 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-KtmfKF4gyIpqYLRqE2N:-KtmfKF4gyIpqYLRqE2O:bszyuh8) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/antool.py#L348)):*
> ```Python
>                 # read data from the file
>                 data_size, info_all, pid_tid, sc_id, timestamp = read_fmt_data(fh, 'IIQQQ')
>                 data_size -= sizeIQQQ
> ```

Should this be 'IQQQ' not 'IIQQQ'? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/340)*

**Comment by ldorau** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/tools/antool/antool.py, line 348 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-KtmfKF4gyIpqYLRqE2N:-Ktofsa_7PBg6HPYeAir:bcan2io) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/antool.py#L348)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Should this be 'IQQQ' not 'IIQQQ'? 
</blockquote></details>

No. I added the comment:
```
# subtract size of all read fields except of the 'data_size' itself
```

---

*[src/tools/antool/listsyscalls.py, line 38 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-Ktm1sLd964RKxIZ6BTa:-KtogzCm4C1fpTR8Fcoh:b-5g0re9) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/listsyscalls.py#L38)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Maybe RESULT_UNSUPPORTED_AT_ALL would be better named as RESULT_NOT_SUPPORTED or simply RESULT_UNSUPPORTED? The 'AT_ALL' seems unnecessary.
</blockquote></details>

It was just changed from ```RESULT_UNSUPPORTED``` to ```RESULT_UNSUPPORTED_AT_ALL``` in PR https://github.com/pmem/pmemfile/pull/328 (12 PRs ago).  Please read the comments: https://github.com/pmem/pmemfile/pull/328#issuecomment-327727701. If you prefer the previous version I can revert this change.

---

*[src/tools/antool/syscall.py, line 178 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-Ktm3F_gBSQzcJK5nRnl:-Ktoi9hUuW28BhrUIcaq:bnick6f) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/syscall.py#L178)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

 This message seems strange. Is it intended to reflect that the input file might be corrupted when processing it? If so, perhaps 'input file may be corrupted' is a  better message.
</blockquote></details>

Is it intended to reflect that the input file could have been corrupted earlier - before processing it. I changed the message as you suggested.

---

*[src/tools/antool/syscall.py, line 191 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-Ktm3VtdWWnFUQwUYW1A:-KtoisTsdTrXMQfdesRp:bnj7hl0) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/syscall.py#L191)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

same as above

---

*[src/tools/antool/syscall.py, line 195 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-Ktm3_H51pvvmmXSednJ:-KtoiuCjFMZ1kH9SNQ69:bnj7hl0) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/syscall.py#L195)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/340)*

**Comment by krzycz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/340)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/tools/antool/listsyscalls.py, line 38 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/340#-Ktm1sLd964RKxIZ6BTa:-KtqQ4MAlTOLWg2CLQCj:b3jx2i2) ([raw file](https://github.com/pmem/pmemfile/blob/a42feccd62c2c638314194bc04c1cb7264b317ef/src/tools/antool/listsyscalls.py#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It was just changed from ```RESULT_UNSUPPORTED``` to ```RESULT_UNSUPPORTED_AT_ALL``` in PR https://github.com/pmem/pmemfile/pull/328 (12 PRs ago).  Please read the comments: https://github.com/pmem/pmemfile/pull/328#issuecomment-327727701. If you prefer the previous version I can revert this change.
</blockquote></details>

It's fine the way it is. I am not going to ask you to change it again :-). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/340)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/340#-:-KtqQYWnZ_XOC4befjyV:bnfp4nl)*

**Pull request merged**
