### PR TITLE
posix: simplify write and pwrite functions

### PR DESCRIPTION
**Pull request by GBuella**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/298)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/298#-:-KrFjxXooPr1v_2hkw1I:bnfp4nl)*

**Comment by marcinslusarz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/libpmemfile-posix/write.c, line 232 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/298#-KrUuDt_o2ZfQccA3dVb:-KrUuDt_o2ZfQccA3dVc:b-kc0kvn) ([raw file](https://github.com/pmem/pmemfile/blob/3f25520e833b5d34519f78db8614e9846e0a0bf2/src/libpmemfile-posix/write.c#L232)):*
> ```C
> {
> 	return pmemfile_writev(pfp, file,
> 			&(pmemfile_iovec_t) {(void *)buf, count}, 1);
> ```

LGTM, but please make a local pmemfile_iovec_t variable. 

---

*[src/libpmemfile-posix/write.c, line 272 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/298#-KrUuOEaQf95eTZU_yM8:-KrUuOEaQf95eTZU_yM9:b-7ropln) ([raw file](https://github.com/pmem/pmemfile/blob/3f25520e833b5d34519f78db8614e9846e0a0bf2/src/libpmemfile-posix/write.c#L272)):*
> ```C
> {
> 	return pmemfile_pwritev(pfp, file,
> 			&(pmemfile_iovec_t) {(void *)buf, count}, 1,
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/298)*

**Comment by GBuella** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libpmemfile-posix/write.c, line 232 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/298#-KrUuDt_o2ZfQccA3dVb:-KrV7bdP-_vUAoymPvR9:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/3f25520e833b5d34519f78db8614e9846e0a0bf2/src/libpmemfile-posix/write.c#L232)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

LGTM, but please make a local pmemfile_iovec_t variable. 
</blockquote></details>

Done.

---

*[src/libpmemfile-posix/write.c, line 272 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/298#-KrUuOEaQf95eTZU_yM8:-KrV7bxHgpiwgvi-aQVC:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/3f25520e833b5d34519f78db8614e9846e0a0bf2/src/libpmemfile-posix/write.c#L272)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/298)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/298#-:-KrVO3T-Fa2dPpaJyh6x:bnfp4nl)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/298#-:-KrWU_cNSCPFv6yPHx6A:bnfp4nl)*

**Pull request merged**
