### PR TITLE
common: fix license in some files

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/304)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/304#-:-KsE9g8mGJ9Uk2mxG1Zs:bnfp4nl)*

**Comment by ldorau** [comment]
Travis build failed:
```
tests/posix/CMakeFiles/gtest.dir/build.make:89: recipe for target 'tests/posix/gtest/src/gtest-stamp/gtest-download' failed
make[2]: *** [tests/posix/gtest/src/gtest-stamp/gtest-download] Error 1
CMakeFiles/Makefile2:1883: recipe for target 'tests/posix/CMakeFiles/gtest.dir/all' failed
make[1]: *** [tests/posix/CMakeFiles/gtest.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/304#-:-KsEFsjvlVy27-5dZBYL:bnfp4nl)*

**Comment by marcinslusarz** [comment]
I restarted the one failing job and it succeeded.

**Pull request merged**
