### PR TITLE
posix: minor fixes for issues raised in #95, part 3

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/157)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/157#-:-KlKYNSqHRelUUJsE08V:bnfp4nl)*

**Comment by marcinslusarz** [comment]
All objects sizes are multiple of 4k. The multiplier for those 3 is 1, but I don't see any problem with changing only one of them.

**Comment by GBuella** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/157#-:-KlYa3d_o_HQxqbO6vqD:bnfp4nl)*

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/157)*

**Pull request merged**
