### PR TITLE
posix: disable verifying timestamps - tm->sec can be negative

### PR DESCRIPTION
**Pull request by szychows**
in POSIX it is valid to have negative value in tm->sec

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/228)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Please make sure code coverage for timestamp.c does not decrease. (Changes in other files can be ignored - they change because of multi-threaded tests)

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/228#-:-KniUlvHWSJ_bTqz_Qo0:bnfp4nl)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/228#-:-KnithIJVBVUcA_x6Dpk:bnfp4nl)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/228#-:-Kntk_DocJ3iJZvLSvru:bnfp4nl)*

**Pull request merged**
