### PR TITLE
Add FUSE driver using libpmemfile-posix.

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/358)

### CODE REVIEW

**Comment by GBuella** [comment]
¿Que?

**Comment by marcinslusarz** [comment]
This is another, more performant, workaround for missing multi-process support.

**Comment by sarahjelinek** [comment]
Reviewed 1 of 3 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/pmemfile-fuse/main.c, line 127 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/358#-KuM7hcG3SiZ715J_ZfI:-KuM7hcG3SiZ715J_ZfJ:b-s7imu4) ([raw file](https://github.com/pmem/pmemfile/blob/46181bec5b6992f26192957a40d2be2ac6d033bb/src/pmemfile-fuse/main.c#L127)):*
> ```C
> 
> 	if (!dir)
> 		return -EINVAL;
> ```

Should the return for this be EBADF?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/358)*

**Comment by marcinslusarz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/pmemfile-fuse/main.c, line 127 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/358#-KuM7hcG3SiZ715J_ZfI:-KuOrH7LL69nEW3urQET:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/46181bec5b6992f26192957a40d2be2ac6d033bb/src/pmemfile-fuse/main.c#L127)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Should the return for this be EBADF?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/358)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/358#-:-KuPBAjKbqPZoOOge2Xe:bnfp4nl)*

**Pull request merged**
