### PR TITLE
Moved Valgrind includes to include directory

### PR DESCRIPTION
**Pull request by szychows**
Moved Valgrind include files from libpmemfile-posix directory to main include directory, so they can be used in other projects which need Valgrind-specific code

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/197)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/197#-:-KmWVDRkkPqrV_r4d_wC:bnfp4nl)*

**Comment by marcinslusarz** [comment]
Hmm, only user visible headers should be in /include. We are not exporting Valgrind headers, so I think they should be in src/valgrind.

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/197#-:-KmXGIytWRaEPT3U0LV0:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/valgrind_internal.h, line 1 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/197#-KmajDyldvQtwDjQWWN8:-KmajDyldvQtwDjQWWN9:b-jzcjkr) ([raw file](https://github.com/pmem/pmemfile/blob/08aeba8d9d224c44595102874f60e028e2e70ad1/src/valgrind_internal.h#L1)):*
> ```objc
> /*
> ```

Wouldn't it be better to have a src/common directory for header files like this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/197)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/valgrind_internal.h, line 1 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/197#-KmajDyldvQtwDjQWWN8:-KmamxnXarm9hBatBuii:b-4ibauj) ([raw file](https://github.com/pmem/pmemfile/blob/08aeba8d9d224c44595102874f60e028e2e70ad1/src/valgrind_internal.h#L1)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Wouldn't it be better to have a src/common directory for header files like this?
</blockquote></details>

I feel like we shouldn't have header files directly under src

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/197)*

**Comment by marcinslusarz** [comment]
*[src/valgrind_internal.h, line 1 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/197#-KmajDyldvQtwDjQWWN8:-KmbBNOL4Ygjlm6o-crs:bxmi64) ([raw file](https://github.com/pmem/pmemfile/blob/08aeba8d9d224c44595102874f60e028e2e70ad1/src/valgrind_internal.h#L1)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

I feel like we shouldn't have header files directly under src
</blockquote></details>

Both locations seem to be fine for me. We already have a header file in src, so I think we need better reason for moving than a feeling ;).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/197)*

**Comment by krzycz** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/197)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/valgrind_internal.h, line 1 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/197#-KmajDyldvQtwDjQWWN8:-Kn5ZW1bLRNJNP3km_4z:b32w0x) ([raw file](https://github.com/pmem/pmemfile/blob/08aeba8d9d224c44595102874f60e028e2e70ad1/src/valgrind_internal.h#L1)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Both locations seem to be fine for me. We already have a header file in src, so I think we need better reason for moving than a feeling ;).
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/197)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/197#-:-Kn5Zi89fBUTjDTJs0ep:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/197)*

**Pull request merged**
