### PR TITLE
posix: drop permission check for timestamp functions

### PR DESCRIPTION
**Pull request by szychows**
Ref: pmem/pmemfile#231

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/232)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/232#-:-Knn8wcj_Z27XV0TI2y4:bnfp4nl)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/232#-:-KnnKEChW8n0f--THoCg:bnfp4nl)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/232#-:-KnnlyeoVfw0pPtdbb5S:bnfp4nl)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/232#-:-KntlLG5J5LFgC_iZ4Co:bnfp4nl)*

**Pull request merged**
