### PR TITLE
posix: change ftruncate errno for readonly file to EINVAL

### PR DESCRIPTION
**Pull request by llugin**
Fixing error occuring in LTP test ftruncate03.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/361)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/361)*

**Comment by marcinslusarz** [comment]
Please add test case for that in tests/posix/rw/rw.cpp/ftruncate

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/361#-:-KuMAsSeEznyKeLQtm2v:bnfp4nl)*

**Comment by krzycz** [comment]
Coverage: -20%. WTH?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/361#-:-KuNrB2JwozohY1zFcdB:bd84cwj)*

**Comment by GBuella** [comment]
Some tests failed. Coverage is reported for failed builds as well? Can we disable that?

**Comment by marcinslusarz** [comment]
I think it's CodeCov.io bug, so no.

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/361#-:-KuP4j-A52eUyKM5MGiB:bnfp4nl)*

**Pull request merged**
