### PR TITLE
posix: fix lseek to end on directory after review

### PR DESCRIPTION
**Pull request by szychows**
Fixes after review

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/288)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libpmemfile-posix/lseek.c, line 183 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/288#-Kqbt2TMLcef0Mtadg6I:-Kqbt2TNdhWtc9vyOxda:b-hdayqm) ([raw file](https://github.com/pmem/pmemfile/blob/a8b0cb05e55ea1e91a1deb1065ad34e51cf1b239/src/libpmemfile-posix/lseek.c#L183)):*
> ```C
> 		for (pmemfile_off_t i = 0; i < dir->num_elements; i++) {
> 			if (dir->dirents[i].name[0] != '\0') {
> 				ret = i + 1;
> ```

ret = i

---

*[src/libpmemfile-posix/lseek.c, line 186 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/288#-Kqbt3qSYj3-4n9wBPkK:-Kqbt3qSYj3-4n9wBPkL:bfflml6) ([raw file](https://github.com/pmem/pmemfile/blob/a8b0cb05e55ea1e91a1deb1065ad34e51cf1b239/src/libpmemfile-posix/lseek.c#L186)):*
> ```C
> 				ret_dir_num = dir_num;
> 
> 				if (ret == dir->num_elements) {
> ```

And this logic should be moved out of both loops.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/288)*

**Comment by szychows** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libpmemfile-posix/lseek.c, line 183 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/288#-Kqbt2TMLcef0Mtadg6I:-Kqc9tpaUzYZTYJRy8f4:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/a8b0cb05e55ea1e91a1deb1065ad34e51cf1b239/src/libpmemfile-posix/lseek.c#L183)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

ret = i
</blockquote></details>

Done.

---

*[src/libpmemfile-posix/lseek.c, line 186 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/288#-Kqbt3qSYj3-4n9wBPkK:-Kqc9u5SPhzw-M6XG0pv:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/a8b0cb05e55ea1e91a1deb1065ad34e51cf1b239/src/libpmemfile-posix/lseek.c#L186)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

And this logic should be moved out of both loops.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/288)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/288#-:-Kqcy5ptqOHkkpzbydnQ:bnfp4nl)*

**Comment by GBuella** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/libpmemfile-posix/lseek.c, line 169 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/288#-Kr6V_KED-uwSsi6R5PP:-Kr6V_KED-uwSsi6R5PQ:b-hchf9e) ([raw file](https://github.com/pmem/pmemfile/blob/c0a1ce0fb2c99b9323d5992b1ba9c7f7f0a6ebad/src/libpmemfile-posix/lseek.c#L169)):*
> ```C
> 	struct pmemfile_dir *dir = &inode->file_data.dir;
> 
> 	struct pmemfile_dir *next = NULL;
> ```

There is no more need to init it to NULL, happens in the loop anyways.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/288#-:-Kr6VkImia8V74LLg-0q:bnfp4nl)*

**Pull request merged**
