### PR TITLE
utils: add scripts to run sqlite tests with option to run with docker

### PR DESCRIPTION
**Pull request by llugin**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/264)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Please integrate it with Travis.

---

Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 46 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQequ0MsQwQtRdAtkV:-KpQequ0MsQwQtRdAtkW:bt8wuku) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L46)):*
> ```Shell
> PF_SQL_UTILS_DIR=$WORKDIR/utils/docker/sqlite
> SQLITE_DIR=$HOME/SQLite-e2d38d51
> SQLITE_LINK=https://www.sqlite.org/src/tarball/SQLite-e2d38d51.tar.gz?uuid=e2d38d51a9cf1c3dfef742507ec76e3d35853bd09b0d09bf2d404c4b036a184d
> ```

Please use released version of Sqlite and install it in the Docker image. 

For example http://sqlite.org/2017/sqlite-src-3190300.zip

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 64 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQgC9fTUAvxbklyZ6H:-KpQgC9g5RuDQH5DU9S1:bthtzw8) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L64)):*
> ```Shell
> export PATH=${TCL_BIN_DIR}:${PATH}
> 
> #install tcl
> ```

Space between # and the rest of the line (here and in other places in this file)

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 78 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQf4w26XdPktqyD_Rr:-KpQf4w26XdPktqyD_Rs:bbtsljo) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L78)):*
> ```Shell
> tar zxf sqlite.tar.gz
> cd $SQLITE_DIR
> ./configure
> ```

You should be able to use TCL from system package.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 84 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQfqrvPwh2OoZKwU-e:-KpQfqrvPwh2OoZKwU-f:b2jwd5t) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L84)):*
> ```Shell
> #install pmemfile
> cd $WORKDIR
> mkdir build; cd build
> ```

single command in one line

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 86 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQfte4K0gxeaNYvDs8:-KpQfte4K0gxeaNYvDs9:b-fzvldl) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L86)):*
> ```Shell
> mkdir build; cd build
> cmake .. -DCMAKE_BUILD_TYPE=Debug \
> 	-DCMAKE_INSTALL_PREFIX=$PMEMFILE_INSTALL_DIR > /dev/null
> ```

Why are you redirecting cmake output to /dev/null?
You don't need to break this line.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 87 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQfImB12o7VmLg0Vxp:-KpQfImB12o7VmLg0Vxq:b-sj9rp1) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L87)):*
> ```Shell
> cmake .. -DCMAKE_BUILD_TYPE=Debug \
> 	-DCMAKE_INSTALL_PREFIX=$PMEMFILE_INSTALL_DIR > /dev/null
> make install -j > /dev/null
> ```

Please don't use -j option without number.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264#-:-KpQgelFjb__kUMEI46g:b-qzsrg4)*

**Comment by krzycz** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 87 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQfImB12o7VmLg0Vxp:-KpQyP7dqFzql-C8hHX3:bb7r2f0) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L87)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please don't use -j option without number.
</blockquote></details>

why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264)*

**Comment by marcinslusarz** [comment]
*[utils/docker/sqlite/run-build-sqlite.sh, line 87 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQfImB12o7VmLg0Vxp:-KpUI3c5s7FBPOhWxOuq:b-k2hwah) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L87)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

why?
</blockquote></details>

From make man page:
"If the -j option is given without an argument, make will not limit the number of jobs that can run simultaneously."

make -j is a great tool for DoS'ing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264)*

**Comment by llugin** [comment]
Review status: 3 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 46 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQequ0MsQwQtRdAtkV:-KpVCbrvTWl2wwuu8zcr:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L46)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please use released version of Sqlite and install it in the Docker image. 

For example http://sqlite.org/2017/sqlite-src-3190300.zip
</blockquote></details>

Done.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 64 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQgC9fTUAvxbklyZ6H:-KpVCdSIjnw6F384WRTQ:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L64)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Space between # and the rest of the line (here and in other places in this file)
</blockquote></details>

Done.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 78 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQf4w26XdPktqyD_Rr:-KpVCe7owwr8ZOZbC6pS:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L78)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

You should be able to use TCL from system package.
</blockquote></details>

Done.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 84 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQfqrvPwh2OoZKwU-e:-KpVCfrlTtqSykvzhJsf:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L84)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

single command in one line
</blockquote></details>

Done.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 86 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQfte4K0gxeaNYvDs8:-KpVCy_PLU19LcemBkDB:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L86)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Why are you redirecting cmake output to /dev/null?
You don't need to break this line.
</blockquote></details>

Done.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 87 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpQfImB12o7VmLg0Vxp:-KpVCz4kgwTgJk6HK3LG:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/4f74e2e400de019441072f33ca7119c3b10e6470/utils/docker/sqlite/run-build-sqlite.sh#L87)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

From make man page:
"If the -j option is given without an argument, make will not limit the number of jobs that can run simultaneously."

make -j is a great tool for DoS'ing.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264)*

**Comment by llugin** [comment]
Integrated with Travis.

---

Review status: 3 of 14 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264#-:-Kp_W_s3HKoWzuUP0gEw:bp22nj3)*

**Comment by krzycz** [comment]
Reviewed 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264)*

**Comment by marcinslusarz** [comment]
Reviewed 9 of 11 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 50 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/264#-Kp_eqTKoD06lGwCnTQ7:-Kp_eqTKoD06lGwCnTQ8:b-qd2zu9) ([raw file](https://github.com/pmem/pmemfile/blob/28c4be65fe9ceb9aab9196b02a29aba64a58b897/utils/docker/sqlite/run-build-sqlite.sh#L50)):*
> ```Shell
> PF_POOL=$PF_DIR/pmemfile_pool
> MOUNTPOINT=$TEST_DIR/mountpoint
> MKFS_PMEMFILE=$WORKDIR/build/src/tools/mkfs.pmemfile
> ```

You are calling "make install", so why not use installed binary?

---

*[utils/docker/sqlite/run-sqlite-testsuite.py, line 56 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/264#-Kp_f1vDTdqeMmVtlIsG:-Kp_f1vEu7FVJFjhDu23:b-jne3h) ([raw file](https://github.com/pmem/pmemfile/blob/28c4be65fe9ceb9aab9196b02a29aba64a58b897/utils/docker/sqlite/run-sqlite-testsuite.py#L56)):*
> ```Python
>         self.pf_env.update({
>             'PMEM_IS_PMEM_FORCE': '1',
>             'LD_PRELOAD': '{}/build/src/libpmemfile/libpmemfile.so'.format(pmemfile_dir),
> ```

Please use installed library.

---

*[utils/docker/sqlite/run-sqlite-testsuite.py, line 199 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/264#-Kp_ffEtqtdZ8q9iJV2E:-Kp_ffEtqtdZ8q9iJV2F:b-z0ybe3) ([raw file](https://github.com/pmem/pmemfile/blob/28c4be65fe9ceb9aab9196b02a29aba64a58b897/utils/docker/sqlite/run-sqlite-testsuite.py#L199)):*
> ```Python
> if __name__ == "__main__":
>     parser = argparse.ArgumentParser(
>         description="Run sqlite tests with pmemfile, vltrace")
> ```

vltrace?

---

*[utils/docker/sqlite/run-sqlite-testsuite.py, line 200 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/264#-Kp_fn_kGflnimrJz_8X:-Kp_fn_kGflnimrJz_8Y:b-3dytma) ([raw file](https://github.com/pmem/pmemfile/blob/28c4be65fe9ceb9aab9196b02a29aba64a58b897/utils/docker/sqlite/run-sqlite-testsuite.py#L200)):*
> ```Python
>     parser = argparse.ArgumentParser(
>         description="Run sqlite tests with pmemfile, vltrace")
>     parser.add_argument("-p", "--pf_pool", required=True,
> ```

--pf-pool

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264)*

**Comment by llugin** [comment]
Review status: 12 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 50 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/264#-Kp_eqTKoD06lGwCnTQ7:-Kpo7lCTRqc05R0h-C59:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/28c4be65fe9ceb9aab9196b02a29aba64a58b897/utils/docker/sqlite/run-build-sqlite.sh#L50)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

You are calling "make install", so why not use installed binary?
</blockquote></details>

Done.

---

*[utils/docker/sqlite/run-sqlite-testsuite.py, line 56 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/264#-Kp_f1vDTdqeMmVtlIsG:-Kpo7mHzD2taefAmX9sU:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/28c4be65fe9ceb9aab9196b02a29aba64a58b897/utils/docker/sqlite/run-sqlite-testsuite.py#L56)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please use installed library.
</blockquote></details>

Done.

---

*[utils/docker/sqlite/run-sqlite-testsuite.py, line 199 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/264#-Kp_ffEtqtdZ8q9iJV2E:-Kpo7n8GfMQ3rUCCqO7X:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/28c4be65fe9ceb9aab9196b02a29aba64a58b897/utils/docker/sqlite/run-sqlite-testsuite.py#L199)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

vltrace?
</blockquote></details>

Done.

---

*[utils/docker/sqlite/run-sqlite-testsuite.py, line 200 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/264#-Kp_fn_kGflnimrJz_8X:-Kpo7nq64igJkXeCDRxG:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/28c4be65fe9ceb9aab9196b02a29aba64a58b897/utils/docker/sqlite/run-sqlite-testsuite.py#L200)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

--pf-pool
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264)*

**Comment by marcinslusarz** [comment]
Reviewed 1 of 2 files at r4.
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 39 at r4](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpoTlZeyY746heETp8c:-KpoTlZeyY746heETp8d:bd5d6lg) ([raw file](https://github.com/pmem/pmemfile/blob/bb0c12a9a23b1c4a2bc470886744ba2449e99d5b/utils/docker/sqlite/run-build-sqlite.sh#L39)):*
> ```Shell
> 
> if [[ -z "$WORKDIR"  ]]; then
>         echo "ERROR: The variable WORKDIR has to contain a path to " \
> ```

indentation

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 66 at r4](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpoSjN2RIIGtecSSfa5:-KpoSjN2RIIGtecSSfa6:b-tr3o8j) ([raw file](https://github.com/pmem/pmemfile/blob/bb0c12a9a23b1c4a2bc470886744ba2449e99d5b/utils/docker/sqlite/run-build-sqlite.sh#L66)):*
> ```Shell
> make install -j2
> 
> export LD_LIBRARY_PATH=${PMEMFILE_INSTALL_DIR}/lib/pmemfile_debug:${LD_LIBRARY_PATH} 
> ```

Space at the end of line.

It means check_whitespace is not executed for this script (and probably the python one). Please fix this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264)*

**Comment by llugin** [comment]
Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 39 at r4](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpoTlZeyY746heETp8c:-Kpp35hMFI6NT1Rm7lkr:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/bb0c12a9a23b1c4a2bc470886744ba2449e99d5b/utils/docker/sqlite/run-build-sqlite.sh#L39)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

indentation
</blockquote></details>

Done.

---

*[utils/docker/sqlite/run-build-sqlite.sh, line 66 at r4](https://reviewable.io:443/reviews/pmem/pmemfile/264#-KpoSjN2RIIGtecSSfa5:-Kpp36tEQkWgUoGBQ8yj:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/bb0c12a9a23b1c4a2bc470886744ba2449e99d5b/utils/docker/sqlite/run-build-sqlite.sh#L66)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Space at the end of line.

It means check_whitespace is not executed for this script (and probably the python one). Please fix this.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/264#-:-KppAGcZCj43VHkLF22Z:bnfp4nl)*

**Pull request merged**
