### PR TITLE
posix: optimize inode size updates for vector writes

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/166)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/166#-:-Kl_d1f81hxnvcdNcKnI:bnfp4nl)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/libpmemfile-posix/write.c, line 183 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/166#-Kl_gCAfSf2LOvLyUmAD:-Kl_gCAfSf2LOvLyUmAE:bxzmbnl) ([raw file](https://github.com/pmem/pmemfile/blob/a402beab1857ada1620978579558dc29f9006809/src/libpmemfile-posix/write.c#L183)):*
> ```C
> 		}
> 
> 		if (ret > 0) {
> ```

Well, yes, the file size does not change when zero bytes are written after a `write(fd, "", 0)` call, I just checked it. So the `ret > 0` condition is correct of course, but could we add a comment here about this edge case? THX

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/166)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/166#-:-Klc48P4OEzwP24bLS4k:bnfp4nl)*

**Comment by marcinslusarz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile-posix/write.c, line 183 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/166#-Kl_gCAfSf2LOvLyUmAD:-KlcAUX1Kk8WK6jgg33S:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/a402beab1857ada1620978579558dc29f9006809/src/libpmemfile-posix/write.c#L183)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Well, yes, the file size does not change when zero bytes are written after a `write(fd, "", 0)` call, I just checked it. So the `ret > 0` condition is correct of course, but could we add a comment here about this edge case? THX
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/166)*

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/166)*

**Comment by GBuella** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/166#-:-KlcPbxzZbxIfuDhyC23:bnfp4nl)*

**Pull request merged**
