### PR TITLE
posix: logging improvements

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/202)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/202#-:-KmlcgtCWO5NvP3OhPGb:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/libpmemfile-posix/out.c, line 180 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/202#-Kn5bUmz__aJcQMvq7OW:-Kn5bUmz__aJcQMvq7OX:b-waqox3) ([raw file](https://github.com/pmem/pmemfile/blob/e0d3702dbe535fa254609e10e8d6f64f68f9b021/src/libpmemfile-posix/out.c#L180)):*
> ```C
> #endif
> 	LOG(LDBG, "%s version %d.%d", log_prefix, major_version, minor_version);
> 	LOG(LDBG, "src version %s", nvml_src_version);
> ```

Why are these two log entries noted as LDBG if they are outside of the #ifdef DEBUG/#endif block?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/202)*

**Comment by marcinslusarz** [comment]
*[src/libpmemfile-posix/out.c, line 180 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/202#-Kn5bUmz__aJcQMvq7OW:-Kn5sVjqxTsi75u5LvTN:b-cx59oz) ([raw file](https://github.com/pmem/pmemfile/blob/e0d3702dbe535fa254609e10e8d6f64f68f9b021/src/libpmemfile-posix/out.c#L180)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why are these two log entries noted as LDBG if they are outside of the #ifdef DEBUG/#endif block?
</blockquote></details>

ifdef DEBUG is not needed for any logging because logging macros print only when DEBUG is defined. You are probably confused by ifdef DEBUG few lines above - it's there because logging macros evaluate its arguments and we don't want to call os_getexecname when it's not needed (it does something non-trivial).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/202)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile-posix/out.c, line 180 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/202#-Kn5bUmz__aJcQMvq7OW:-Kn5w8Yo2z2_lX2hXmaW:b2k6ukr) ([raw file](https://github.com/pmem/pmemfile/blob/e0d3702dbe535fa254609e10e8d6f64f68f9b021/src/libpmemfile-posix/out.c#L180)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

ifdef DEBUG is not needed for any logging because logging macros print only when DEBUG is defined. You are probably confused by ifdef DEBUG few lines above - it's there because logging macros evaluate its arguments and we don't want to call os_getexecname when it's not needed (it does something non-trivial).
</blockquote></details>

oh ok. makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/202)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile-posix/out.c, line 180 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/202#-Kn5bUmz__aJcQMvq7OW:-Kn5wNfKgJGDQ4PfNwHy:bg7igkv) ([raw file](https://github.com/pmem/pmemfile/blob/e0d3702dbe535fa254609e10e8d6f64f68f9b021/src/libpmemfile-posix/out.c#L180)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

oh ok. makes sense.
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/202)*

**Comment by sarahjelinek** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/202)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/202#-:-Kn5werKjbntDWfMIf9r:bnfp4nl)*

**Pull request merged**
