### PR TITLE
tests: fix xattr.h include directive

### PR DESCRIPTION
**Pull request by GBuella**
Ref: #252

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/253)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Please also revert libattr1-dev installation from Docker images.

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/253#-:-KpFNLz80xxCLUpo8Tgo:bnfp4nl)*

**Comment by marcinslusarz** [comment]
*[tests/preload/xattr/xattr.c, line 48 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/253#-KpFqXRE3_gO0qf0ErWY:-KpFqXRE3_gO0qf0ErWZ:b-78jn4r) ([raw file](https://github.com/pmem/pmemfile/blob/bb5140ce4bf077d5345c4631a13160164b7cede7/tests/preload/xattr/xattr.c#L48)):*
> ```C
> #include <sys/types.h>
> #include <unistd.h>
> #include <sys/xattr.h>
> ```

If this file is not buggy anymore you should a) put it in a proper place in the include list and trim the list of header files. If it still is, then don't remove the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/253)*

**Comment by GBuella** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/preload/xattr/xattr.c, line 48 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/253#-KpFqXRE3_gO0qf0ErWY:-KpFwD1ZLq4hYL88EgoR:b-wdvs84) ([raw file](https://github.com/pmem/pmemfile/blob/bb5140ce4bf077d5345c4631a13160164b7cede7/tests/preload/xattr/xattr.c#L48)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

If this file is not buggy anymore you should a) put it in a proper place in the include list and trim the list of header files. If it still is, then don't remove the comment.
</blockquote></details>

I managed to get rid of `stddef.h`. The others are needed for PATH_MAX, open, sprintf, etc...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/253)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/253#-:-KpG1ZmcZzr7RhlEfFf4:bnfp4nl)*

**Comment by marcinslusarz** [comment]
@sarahjelinek Please take a look at this PR ASAP. It's affecting all Jenkins jobs.

**Comment by ldorau** [comment]
🥇  👍

**Comment by ldorau** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/253#-:-KpKvzZ0UvMmjUlSH1ae:bnfp4nl)*

**Pull request merged**
