### PR TITLE
doc: extend "limitations" section

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/260)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/260#-:-KpLD8uT2iab-jp8iOjE:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[README.md, line 97 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/260#-KpLnNs5ddXlAd-vCrhS:-KpLnNs5ddXlAd-vCrhT:bvob630) ([raw file](https://github.com/pmem/pmemfile/blob/542300069d294de8458a5f94609d2f88c84fdc67/README.md#L97)):*
> ```Markdown
>   and libpmemobj limitation)
> * libpmemfile.so is not safe with remotely replicated pool (libpmemfile-posix.so
>   has no such limitation)
> ```

I think we should add why it's not safe. A short paragraph is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/260)*

**Comment by GBuella** [comment]
Perhaps we should add some note about the transparent libpmemfile.so usage not being signal safe, i.e. your syscalls issued in signal handlers might lead to deadlocks and whatnot. The only thing is, who is going to check for syscalls in signal handlers, when we claim libpmemfile.so can be used without altering programs? Do we state "one doesn't need to alter source code, but surely must read the source of one's program before using pmemfile"?

**Comment by marcinslusarz** [comment]
IIRC we discussed a plan how to address signal safety. Limitations section lists only stuff we don't intend to fix or are outside of this project control. Everything else is a bug or not yet implemented feature.
Without this distinction this list would have to include all bugs...

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 97 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/260#-KpLnNs5ddXlAd-vCrhS:-KpPd6foKK2KMqAJQGaV:b-7njket) ([raw file](https://github.com/pmem/pmemfile/blob/542300069d294de8458a5f94609d2f88c84fdc67/README.md#L97)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

I think we should add why it's not safe. A short paragraph is fine.
</blockquote></details>

I'm not sure how to explain that without diving into details and not scaring users. Suggestions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/260#-:-KpPdW3-BITwFgMlbzFd:b-itoxgx)*

**Comment by sarahjelinek** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 97 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/260#-KpLnNs5ddXlAd-vCrhS:-KpQP1C70HdOXxoVUFHs:b-pqfw44) ([raw file](https://github.com/pmem/pmemfile/blob/542300069d294de8458a5f94609d2f88c84fdc67/README.md#L97)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I'm not sure how to explain that without diving into details and not scaring users. Suggestions?
</blockquote></details>

No, actually, you are right. I think what you are saying is correct. I think it's fine the way it is. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/260)*

**Pull request merged**
