### PR TITLE
preload: fix truncate for paths outside of pmemfile pool

### PR DESCRIPTION
**Pull request by marcinslusarz**
... when path crosses pmemfile mount point

Ref: #306

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/337)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/337#-:-KtVJmN2nJ6zWLkaXfiM:bnfp4nl)*

**Comment by GBuella** [comment]
Could you add a test which truncates a file outside a pool?
I'm curious about what codecov will say. Right now, it reports 50% of the diff is covered.

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/337#-:-KtXhqiuPtr6jzHSGY_L:bnfp4nl)*

**Comment by GBuella** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/337#-:-KtlMuGgqcv6bs7mw5je:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/337)*

**Pull request merged**
