### PR TITLE
Fixes for issues raised in #95, part 2

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/150)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/libpmemfile-posix.h, line 156 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/150#-Kkywqc0R8sWn9gtCiDY:-Kkywqc0R8sWn9gtCiDZ:bm0zytb) ([raw file](https://github.com/pmem/pmemfile/blob/39fab462e6642263c809987de9a700839ae75aab/include/libpmemfile-posix.h#L156)):*
> ```objc
> #define PMEMFILE_F_OK 0
> 
> #define PMEMFILE_FALLOC_FL_KEEP_SIZE       0x01
> ```

Do we need "FL" in the flag names?

---

*[src/libpmemfile-posix/dir.c, line 633 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/150#-Kkyy4JnFtGwPoMDCbki:-Kkyy4JnFtGwPoMDCbkj:bxnd4za) ([raw file](https://github.com/pmem/pmemfile/blob/39fab462e6642263c809987de9a700839ae75aab/src/libpmemfile-posix/dir.c#L633)):*
> ```C
> 	size_t namelen = strlen(dirent->name);
> 	unsigned short slen =
> 		(unsigned short) (8 + 8 + 2 + namelen + 1 + 1);
> ```

any comment on why  8+8+2+1+1 ?

---

*[src/libpmemfile-posix/dir.c, line 668 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkyyCJcPL5rRz3w0O69:-KkyyCJcPL5rRz3w0O6A:b32v1h) ([raw file](https://github.com/pmem/pmemfile/blob/39fab462e6642263c809987de9a700839ae75aab/src/libpmemfile-posix/dir.c#L668)):*
> ```C
> 	size_t namelen = strlen(dirent->name);
> 	unsigned short slen =
> 		(unsigned short) (8 + 8 + 2 + 1 + namelen + 1);
> ```

''

---

*[tests/posix/pmemfile_test.cpp, line 251 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/150#-Kkyw4sY066DNjngDsqL:-Kkyw4sY066DNjngDsqM:b-hvsdu6) ([raw file](https://github.com/pmem/pmemfile/blob/39fab462e6642263c809987de9a700839ae75aab/tests/posix/pmemfile_test.cpp#L251)):*
> ```cpp
> 		VAL_EXPECT_EQ(c.mode, attrs.stat.st_mode);
> 		VAL_EXPECT_EQ(c.nlink, attrs.stat.st_nlink);
> 		bool check_size = true;
> ```

why not just a single if() ?
```c
if (!PMEMFILE_S_ISDIR(attrs.stat.st_mode) || check_dir_size)
        VAL_EXPECT_EQ(c.size, attrs.stat.st_size);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/150)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/libpmemfile-posix.h, line 156 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/150#-Kkywqc0R8sWn9gtCiDY:-Kkz7HK4nIBR_ovG44P5:bz1fw7j) ([raw file](https://github.com/pmem/pmemfile/blob/39fab462e6642263c809987de9a700839ae75aab/include/libpmemfile-posix.h#L156)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

Do we need "FL" in the flag names?
</blockquote></details>

This keeps the flags similar to the ones used for fallocate in libc, see:
`man 2 fallocate`

---

*[tests/posix/pmemfile_test.cpp, line 251 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/150#-Kkyw4sY066DNjngDsqL:-Kkz7j7-xPLd3HTCelKe:b2ngl7l) ([raw file](https://github.com/pmem/pmemfile/blob/39fab462e6642263c809987de9a700839ae75aab/tests/posix/pmemfile_test.cpp#L251)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

why not just a single if() ?
```c
if (!PMEMFILE_S_ISDIR(attrs.stat.st_mode) || check_dir_size)
        VAL_EXPECT_EQ(c.size, attrs.stat.st_size);
```
</blockquote></details>

 +1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/150)*

**Comment by marcinslusarz** [comment]
Review status: 28 of 31 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/libpmemfile-posix/dir.c, line 633 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/150#-Kkyy4JnFtGwPoMDCbki:-KkzEUtxSA7LfgIeFN0w:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/39fab462e6642263c809987de9a700839ae75aab/src/libpmemfile-posix/dir.c#L633)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

any comment on why  8+8+2+1+1 ?
</blockquote></details>

Done.

---

*[src/libpmemfile-posix/dir.c, line 668 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkyyCJcPL5rRz3w0O69:-KkzEVoog21Nzpl6tcI0:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/39fab462e6642263c809987de9a700839ae75aab/src/libpmemfile-posix/dir.c#L668)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

''
</blockquote></details>

Done.

---

*[tests/posix/pmemfile_test.cpp, line 251 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/150#-Kkyw4sY066DNjngDsqL:-KkzAkEA7GM956arzJ1e:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/39fab462e6642263c809987de9a700839ae75aab/tests/posix/pmemfile_test.cpp#L251)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

 +1
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/150)*

**Comment by GBuella** [comment]
Reviewed 1 of 31 files at r1, 1 of 3 files at r2.
Review status: 29 of 31 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/150)*

**Comment by GBuella** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/150)*

**Comment by GBuella** [comment]
Reviewed 17 of 31 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/libpmemfile-posix/internal.h, line 75 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzK71CpYhG0scCvOVD:-KkzK71CpYhG0scCvOVE:bev6sj1) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/src/libpmemfile-posix/internal.h#L75)):*
> ```objc
> }
> 
> void verify_consts(void);
> ```

What for?

---

*[src/libpmemfile-posix/pmemfile-posix.c, line 106 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzKLGMEVaIw9rUJQMf:-KkzKLGMEVaIw9rUJQMg:bev6sj1) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/src/libpmemfile-posix/pmemfile-posix.c#L106)):*
> ```C
> 	    (pmemfile_overallocate_on_append ? "set" : "not set"));
> 
> 	verify_consts();
> ```

What for?

---

*[src/libpmemfile-posix/stubs.c, line 37 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzKUGHLkQV4e90boe_:-KkzKUGHLkQV4e90boea:bd95i6t) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/src/libpmemfile-posix/stubs.c#L37)):*
> ```C
>  * pmemfile that is not yet implemented.
>  * All these set errno to ENOTSUP.
>  */
> ```

But it is cool.
Ah, nevermind...

---

*[tests/helpers.cmake, line 42 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzLA6k0Y3Bo3xysQEy:-KkzLA6k0Y3Bo3xysQEz:b-hd2uwa) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/tests/helpers.cmake#L42)):*
> ```CMake
> endfunction()
> 
> # Cleans up environment.
> ```

These comments here are remind me of:
```
a++; /* increment the numerical value stored in 'a' by one */
```

Perhaps we could
  * either not add comments
  * or explain which directories must setup and why, and explain why the BIN_DIR doesn't need to be removed during cleanup

---

*[tests/helpers.cmake, line 47 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzM2RqBLJr-7NPZf_4:-KkzM2Rro1MCiFhLX7G5:b2khm3c) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/tests/helpers.cmake#L47)):*
> ```CMake
> endfunction()
> 
> # Creates pool.
> ```

Creates a pool? I would never have guessed that!

---

*[tests/helpers.cmake, line 101 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzMJoEzFnPVrIBBD3j:-KkzMJoEzFnPVrIBBD3k:b-ndaz4h) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/tests/helpers.cmake#L101)):*
> ```CMake
> endfunction()
> 
> # Generic command executor which handles failures.
> ```

"...which stop the tests if the executed process returns a non-zero return value -- useful, as the tests ignore such failures by default."

---

*[tests/helpers.cmake, line 129 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzMeofoKwMIA2mE2_c:-KkzMeofoKwMIA2mE2_d:b-swk3ei) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/tests/helpers.cmake#L129)):*
> ```CMake
> endfunction()
> 
> # Compares 2 files using "cmp" command.
> ```

Oh really? I could never figure that out by looking at the function body!

It could use '$(CMAKE_COMMAND) -E compare_files' btw.
Or are these (cmp, mkdir, rmdir, etc...) supposed to test the platform's binaries with LD_PRELOAD-ed pmemfile? Then add that as comment please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/150)*

**Comment by krzycz** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/150)*

**Comment by marcinslusarz** [comment]
Review status: 27 of 30 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/libpmemfile-posix/internal.h, line 75 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzK71CpYhG0scCvOVD:-KkzxxS1jgfg8vwzyz-X:b-cgj4lz) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/src/libpmemfile-posix/internal.h#L75)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

What for?
</blockquote></details>

See commit description.

---

*[src/libpmemfile-posix/pmemfile-posix.c, line 106 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzKLGMEVaIw9rUJQMf:-Kkzy0kzW3t6jzZ7Mwwx:b-89a4l7) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/src/libpmemfile-posix/pmemfile-posix.c#L106)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

What for?
</blockquote></details>

Ditto

---

*[tests/helpers.cmake, line 42 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzLA6k0Y3Bo3xysQEy:-Kkzy49sRIBXHCAzQ-rD:bctv2f4) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/tests/helpers.cmake#L42)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

These comments here are remind me of:
```
a++; /* increment the numerical value stored in 'a' by one */
```

Perhaps we could
  * either not add comments
  * or explain which directories must setup and why, and explain why the BIN_DIR doesn't need to be removed during cleanup
</blockquote></details>

As discussed I removed all trivial descriptions.

---

*[tests/helpers.cmake, line 47 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzM2RqBLJr-7NPZf_4:-Kkzy8U4twxjM-89CTDN:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/tests/helpers.cmake#L47)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Creates a pool? I would never have guessed that!
</blockquote></details>

Done.

---

*[tests/helpers.cmake, line 101 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzMJoEzFnPVrIBBD3j:-Kkzy967-5xNVl9PI70S:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/tests/helpers.cmake#L101)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

"...which stop the tests if the executed process returns a non-zero return value -- useful, as the tests ignore such failures by default."
</blockquote></details>

Done.

---

*[tests/helpers.cmake, line 129 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/150#-KkzMeofoKwMIA2mE2_c:-Kkzy9ppai3xsNMQUw81:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/2f0ce8df9eab5d10b6592da7d8ee85ba0b73baca/tests/helpers.cmake#L129)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Oh really? I could never figure that out by looking at the function body!

It could use '$(CMAKE_COMMAND) -E compare_files' btw.
Or are these (cmp, mkdir, rmdir, etc...) supposed to test the platform's binaries with LD_PRELOAD-ed pmemfile? Then add that as comment please.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/150)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/150#-:-Kl-gbczqDmiwvgS8dgu:bnfp4nl)*

**Comment by GBuella** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/150#-:-Kl3DXbunzD_ONshX6Rd:bnfp4nl)*

**Pull request merged**
