### PR TITLE
WIP: antool: add more tests and some fixes

### PR DESCRIPTION
**Pull request by ldorau**
It will increase antool's code coverage more than 18% (from about 75.03% to about 93%).

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/327)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Reviewed 4 of 5 files at r1, 2 of 43 files at r4.
Review status: 6 of 47 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/327)*

**Comment by ldorau** [comment]
The code will be moved to another PR.

**Comment by ldorau** [comment]
https://github.com/pmem/pmemfile/pull/340

**Comment by ldorau** [comment]
https://github.com/pmem/pmemfile/pull/341

**Pull request closed without merging**
