### PR TITLE
antool: fix antool fault injection tests with vltrace

### PR DESCRIPTION
**Pull request by ldorau**
Antool's fault injection tests use one binary log file as an input file,
so this one file has to be decompressed also when vltrace is run.
This patch adds this functionality.

Antool's fault injection tests have been failing so far
if they were run with vltrace, because vltrace overwrote their input file.
This patch fixes this issue.

This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/376)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/376)*

**Comment by ldorau** [comment]
Antool's fault injection tests use one binary log file as an input file,
so this one file has to be decompressed also when vltrace is run.
This patch adds this functionality.

Antool's fault injection tests have been failing so far
if they were run with vltrace, because vltrace overwrote their input file.
This patch fixes this issue.

**Comment by krzycz** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/376)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 7 of 7 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/376#-:-KuymEbqH1Ht9L3A-TDV:bnfp4nl)*

**Pull request merged**
