### PR TITLE
preload: remove unused "strict symlink" code

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/139)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/139#-:-KkQCRlIQ0w8j6ZFjgwf:bnfp4nl)*

**Comment by GBuella** [comment]
So we don't plan on using this eventually?
This would allow for much faster path resolution optionally, we would just need to check this flag in path_resolve.c

**Comment by marcinslusarz** [comment]
I don't know. I spotted unused code which looked like a leftover, so I made a PR which removes it. Do you plan to implement it soon?

**Comment by GBuella** [comment]
Well, I guess if we would like to use this anyways, we can always find it in the git history. I hope we can, unlike the stuff left over in nvml/pmemfile.v12 .

So, yes, let's remove this now.

**Pull request merged**
