### PR TITLE
preload: fix how paths crossing pmemfile mount point are handled

### LINKED ISSUE #181: preload: some syscalls fail for relative paths, even when path does not point to pmemfile
This includes: chroot, listxattr, removexattr, llistxattr, lremovexattr, ~~utime, utimes~~.

### PR DESCRIPTION
**Pull request by marcinslusarz**
Bind (for unix sockets) was not handled at all. For getxattr, setxattr, listxattr, llistxattr, removexattr, lremovexattr and chroot paths that pointed outside of pmemfile pool but crossed pmemfile mount point (/mnt/pmemfile/../../tmp/file) were handled incorrectly.

Fixes #181.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/238)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libpmemfile/path_resolve.c, line 415 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/238#-KohKwNFd5tQVQd1weiT:-KohKwNGSgU-xbhmf9sk:biy1821) ([raw file](https://github.com/pmem/pmemfile/blob/c2ffc1f8f1c090300e88602b8d28e40e5d591d93/src/libpmemfile/path_resolve.c#L415)):*
> ```C
> 	 * pmemfile and is relative to a mount point and user wants path for
> 	 * interfaces that do not have *at variant, then prepend the path with
> 	 * the mount point path.
> ```

A Q: why does a *at variant matter here?

---

*[src/libpmemfile/path_resolve.c, line 427 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/238#-KohLSpClHUPp5Z_TqXH:-KohLSpClHUPp5Z_TqXI:bta6e7h) ([raw file](https://github.com/pmem/pmemfile/blob/c2ffc1f8f1c090300e88602b8d28e40e5d591d93/src/libpmemfile/path_resolve.c#L427)):*
> ```C
> 		}
> 
> 		memmove(result->path + mnt_len + 1, result->path, rem_len + 1);
> ```

Why memmove()? Is it possible the memory areas will overlap here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/238)*

**Comment by GBuella** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/libpmemfile/path_resolve.c, line 415 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/238#-KohKwNFd5tQVQd1weiT:-KokuXQMicsl2Mwbbz3k:b-i5dzl7) ([raw file](https://github.com/pmem/pmemfile/blob/c2ffc1f8f1c090300e88602b8d28e40e5d591d93/src/libpmemfile/path_resolve.c#L415)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

A Q: why does a *at variant matter here?
</blockquote></details>

Because generally we translate calls such as `open` to their *_at counterpart, e.g. `openat`. But we can not do this with some syscalls, e.g.:  `getxattr`.  So, if the user has a CWD inside pmemfile calls `getxattr("../../../a/b", name, value, size)`,  we can not translate it to something like `getxattr_at(mount_point, "../a/b", ...)` to the kernel, as we would normally do, since `getxattr_at` doesn't exist.  So we need some other way to forward this to the kernel.

---

*[tests/preload/unix/unix.c, line 2 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/238#-Kokvxv3vuJU5LsACzKg:-Kokvxv3vuJU5LsACzKh:bvbnxpv) ([raw file](https://github.com/pmem/pmemfile/blob/c2ffc1f8f1c090300e88602b8d28e40e5d591d93/tests/preload/unix/unix.c#L2)):*
> ```C
> /*
>  * Copyright 2016-2017, Intel Corporation
> ```

Only 2017 I guess

---

*[utils/docker/images/Dockerfile.ubuntu-17.04, line 53 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/238#-Kokwcx2pPTWtuX5tStE:-Kokwcx2pPTWtuX5tStF:b-8f6pxs) ([raw file](https://github.com/pmem/pmemfile/blob/c2ffc1f8f1c090300e88602b8d28e40e5d591d93/utils/docker/images/Dockerfile.ubuntu-17.04#L53)):*
> ```
> 	doxygen \
> 	git \
> 	libattr1-dev \
> ```

So what is this used for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/238)*

**Comment by marcinslusarz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/libpmemfile/path_resolve.c, line 427 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/238#-KohLSpClHUPp5Z_TqXH:-Kolfsrt-nO-Q0MEyFSW:bzdtlv5) ([raw file](https://github.com/pmem/pmemfile/blob/c2ffc1f8f1c090300e88602b8d28e40e5d591d93/src/libpmemfile/path_resolve.c#L427)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why memmove()? Is it possible the memory areas will overlap here?
</blockquote></details>

Yes, it's quite possible they will overlap. 

---

*[tests/preload/unix/unix.c, line 2 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/238#-Kokvxv3vuJU5LsACzKg:-KolcWWMe7gxepsyflPM:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/c2ffc1f8f1c090300e88602b8d28e40e5d591d93/tests/preload/unix/unix.c#L2)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Only 2017 I guess
</blockquote></details>

Done.

---

*[utils/docker/images/Dockerfile.ubuntu-17.04, line 53 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/238#-Kokwcx2pPTWtuX5tStE:-KolcZ_6RvKCYt2u7No7:b4kmqq) ([raw file](https://github.com/pmem/pmemfile/blob/c2ffc1f8f1c090300e88602b8d28e40e5d591d93/utils/docker/images/Dockerfile.ubuntu-17.04#L53)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

So what is this used for?
</blockquote></details>

It's needed by tests/preload/xattr/xattr.c

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/238)*

**Comment by GBuella** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/238#-:-KolmBhZM2DVMV7-LjbO:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Reviewed 14 of 16 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/libpmemfile/path_resolve.c, line 415 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/238#-KohKwNFd5tQVQd1weiT:-KongD307Gee48hfs_AD:b32w0x) ([raw file](https://github.com/pmem/pmemfile/blob/c2ffc1f8f1c090300e88602b8d28e40e5d591d93/src/libpmemfile/path_resolve.c#L415)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Because generally we translate calls such as `open` to their *_at counterpart, e.g. `openat`. But we can not do this with some syscalls, e.g.:  `getxattr`.  So, if the user has a CWD inside pmemfile calls `getxattr("../../../a/b", name, value, size)`,  we can not translate it to something like `getxattr_at(mount_point, "../a/b", ...)` to the kernel, as we would normally do, since `getxattr_at` doesn't exist.  So we need some other way to forward this to the kernel.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/238)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/238#-:-KongWHRx66ZiczPQ4PO:bnfp4nl)*

**Comment by GBuella** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/238)*

**Comment by marcinslusarz** [comment]
@sarahjelinek Is there anything blocking merge of this PR?

**Pull request merged**
