### PR TITLE
posix: fix F_SETFD return statement

### PR DESCRIPTION
**Pull request by llugin**
Ref: #162

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/164)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile-posix/fcntl.c, line 71 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/164#-KlY0JQL0EK2G8YyaAUn:-KlY0JQL0EK2G8YyaAUo:bw1ejtu) ([raw file](https://github.com/pmem/pmemfile/blob/ab21b9548ff48099d9373da36bb83410ef434dfd/src/libpmemfile-posix/fcntl.c#L71)):*
> ```C
> 				return PMEMFILE_O_PATH;
> 
> 			int ret = 0;
> ```

That's unrelated change. If you really want to do that then add braces for the whole case block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/164)*

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/164)*

**Comment by llugin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile-posix/fcntl.c, line 71 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/164#-KlY0JQL0EK2G8YyaAUn:-KlYMMMPaJKMNkkaxJM4:bb7f2mf) ([raw file](https://github.com/pmem/pmemfile/blob/ab21b9548ff48099d9373da36bb83410ef434dfd/src/libpmemfile-posix/fcntl.c#L71)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

That's unrelated change. If you really want to do that then add braces for the whole case block.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/164)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/164#-:-KlYQbIRPJ8yqiZ9v74j:bnfp4nl)*

**Pull request merged**
