### PR TITLE
preload: credentials & umask

### PR DESCRIPTION
**Pull request by marcinslusarz**
Ref: pmem/pmemfile#207

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/212)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
I haven't tested it with anything that changes credentials. Let's merge this first (with all other preload fixes that affect pjdfstest) and then I'll fix remaining issues. There's too much stuff broken in libpmemfile to test individual fixes with full test suite.

**Comment by sarahjelinek** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile/preload.c, line 1276 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/212#-Kn6S5hFR5VJZ2AXnSrC:-Kn6S5hFR5VJZ2AXnSrD:b-dxrxcx) ([raw file](https://github.com/pmem/pmemfile/blob/03f09effa9d9283fb6949938a677a031d3aedcc1/src/libpmemfile/preload.c#L1276)):*
> ```C
> 			continue;
> 		if (pmemfile_setfsuid(p->pool, fsuid) != old)
> 			FATAL("inconsistent fsuid state");
> ```

If for some reason the fsuid, or other XXuid fields are corrupted in the pfp header does this FATAL mean that we stop operation and that somehow the user would have to fix this issue?  

I guess my most basic question is that at this point I don't see that we have an 'error' bit in the super block structure which tells us that a pmemfile fs can be 'mounted'.  We can fail here but nothing i can see prevents the process from being restarted and continuing.  Unless I am missing something. It doesn't just apply to this area. I was just thinking about this and how we can and should indicate an error state. For example, let's say there is some corruption like this shouldn't we open the pool read only?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/212)*

**Comment by marcinslusarz** [comment]
*[src/libpmemfile/preload.c, line 1276 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/212#-Kn6S5hFR5VJZ2AXnSrC:-Kn9GSfKCI5e3ldt-aD1:boo2oap) ([raw file](https://github.com/pmem/pmemfile/blob/03f09effa9d9283fb6949938a677a031d3aedcc1/src/libpmemfile/preload.c#L1276)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

If for some reason the fsuid, or other XXuid fields are corrupted in the pfp header does this FATAL mean that we stop operation and that somehow the user would have to fix this issue?  

I guess my most basic question is that at this point I don't see that we have an 'error' bit in the super block structure which tells us that a pmemfile fs can be 'mounted'.  We can fail here but nothing i can see prevents the process from being restarted and continuing.  Unless I am missing something. It doesn't just apply to this area. I was just thinking about this and how we can and should indicate an error state. For example, let's say there is some corruption like this shouldn't we open the pool read only?
</blockquote></details>

This is runtime state. If it's inconsistent it means there's a pretty significant bug somewhere or real syscall behaves in an unexpected way. I'd like to get a bug report if that's possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/212)*

**Comment by sarahjelinek** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/libpmemfile/preload.c, line 1276 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/212#-Kn6S5hFR5VJZ2AXnSrC:-Kn9pqbJ80b-i_i3vA8n:bxw4rnd) ([raw file](https://github.com/pmem/pmemfile/blob/03f09effa9d9283fb6949938a677a031d3aedcc1/src/libpmemfile/preload.c#L1276)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

This is runtime state. If it's inconsistent it means there's a pretty significant bug somewhere or real syscall behaves in an unexpected way. I'd like to get a bug report if that's possible.
</blockquote></details>

OK. Fair point. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/212)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/212#-:-Kn9zPZRbRreOX4CdKrU:bnfp4nl)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: 10 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/212#-:-KnBe3KNTWzYj4RFJKJb:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Reviewed 10 of 13 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/212)*

**Pull request merged**
