### PR TITLE
tests: fixed pool_locking.c fd leak

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/250)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/250#-:-Kp0S6MDchu13xVHEBpU:bnfp4nl)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[tests/preload/pool_locking/pool_locking.c, line 52 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/250#-Kp0VR6GO4QJFqcH6tpG:-Kp0VR6GO4QJFqcH6tpH:b9q5l4h) ([raw file](https://github.com/pmem/pmemfile/blob/a71bf18ea929513441b7b6968c0e4355f9553f3d/tests/preload/pool_locking/pool_locking.c#L52)):*
> ```C
> 		close(fd);
> 
> 		int new_fd = open(filename, O_RDWR);
> ```

Might also wanna check for success here:
```
if (new_fd < 0)
    err(1, "open(\"%s\", O_RDWR)");
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/250)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/preload/pool_locking/pool_locking.c, line 52 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/250#-Kp0VR6GO4QJFqcH6tpG:-Kp0VpttOKepYKRzLFAZ:b34uuq1) ([raw file](https://github.com/pmem/pmemfile/blob/a71bf18ea929513441b7b6968c0e4355f9553f3d/tests/preload/pool_locking/pool_locking.c#L52)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Might also wanna check for success here:
```
if (new_fd < 0)
    err(1, "open(\"%s\", O_RDWR)");
```
</blockquote></details>

I meant:
```
if (new_fd < 0)
    err(1, "open(\"%s\", O_RDWR)", filename);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/250)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/250#-:-Kp0ih0JvrVhAI0xAaMq:bnfp4nl)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/250#-:-Kp1mwJhxMynzTphWvo0:bnfp4nl)*

**Comment by igchor** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/preload/pool_locking/pool_locking.c, line 52 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/250#-Kp0VR6GO4QJFqcH6tpG:-KpsY4kccwXt8sCPLFAz:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/a71bf18ea929513441b7b6968c0e4355f9553f3d/tests/preload/pool_locking/pool_locking.c#L52)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

I meant:
```
if (new_fd < 0)
    err(1, "open(\"%s\", O_RDWR)", filename);
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/250)*

**Pull request merged**
