### PR TITLE
utils: add support for CXX to docker scripts

### PR DESCRIPTION
**Pull request by mramotowski**
#224

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/225)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 7 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/225#-Knd1XxAJ1sZANJQV8rl:-Knd1XxAJ1sZANJQV8rm:b-fwm10u) ([raw file](https://github.com/pmem/pmemfile/blob/9ea511c182d7253ec8838d01e252b8c747c739a0/.travis.yml#L7)):*
> ```YAML
>     - MAKE_PKG=1 OS=ubuntu OS_VER=16.04
>     - MAKE_PKG=1 OS=fedora OS_VER=25
>     - MAKE_PKG=0 OS=ubuntu OS_VER=16.04 COMPILER=clang COMPILER=clang++
> ```

Did you mean **COMPILERXX** ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/225#-:-Knd1pZxrsnUVBV0Hy_q:bnfp4nl)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/225#-:-KnddhMBPiPXo8JdEwlU:bnfp4nl)*

**Comment by mramotowski** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 7 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/225#-Knd1XxAJ1sZANJQV8rl:-KnijVkn00PL0i2vFohD:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/9ea511c182d7253ec8838d01e252b8c747c739a0/.travis.yml#L7)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

Did you mean **COMPILERXX** ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/225)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/225#-:-KniptlfXevSbqpoyhEk:bnfp4nl)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/225#-:-Kno5im1wnJc3x0vH4Sn:bnfp4nl)*

**Pull request merged**
