### PR TITLE
Coverity fixes / annotations

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/194)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile-posix/fallocate.c, line 119 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/194#-Km6PjMLt8eQTgk70UWs:-Km6PjMLt8eQTgk70UWt:b-eu9x94) ([raw file](https://github.com/pmem/pmemfile/blob/d86bafa87b735c988f399132b6037156ab7b012c/src/libpmemfile-posix/fallocate.c#L119)):*
> ```C
> 	 * "EFBIG - offset+len exceeds the maximum file size."
> 	 */
> 	if ((size_t)offset + (size_t)length > (size_t)SSIZE_MAX)
> ```

what about `if ((size_t)offset > (size_t)SSIZE_MAX - (size_t)length) ...`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/194)*

**Comment by marcinslusarz** [comment]
*[src/libpmemfile-posix/fallocate.c, line 119 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/194#-Km6PjMLt8eQTgk70UWs:-Km6_ysGxnCyowwD5omz:b7gnndr) ([raw file](https://github.com/pmem/pmemfile/blob/d86bafa87b735c988f399132b6037156ab7b012c/src/libpmemfile-posix/fallocate.c#L119)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

what about `if ((size_t)offset > (size_t)SSIZE_MAX - (size_t)length) ...`
</blockquote></details>

Both offset and length are signed, so it's equivalent. It's less readable so I'd opt for my version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/194)*

**Comment by krzycz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/libpmemfile-posix/fallocate.c, line 119 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/194#-Km6PjMLt8eQTgk70UWs:-Km6bp41MFI39565drqo:b5q8s3g) ([raw file](https://github.com/pmem/pmemfile/blob/d86bafa87b735c988f399132b6037156ab7b012c/src/libpmemfile-posix/fallocate.c#L119)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Both offset and length are signed, so it's equivalent. It's less readable so I'd opt for my version.
</blockquote></details>

My point was that in my version you can avoid overflow. But if offset and length are signed but positive number, it won't happen anyway, so your version is also fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/194)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/194#-:-Km7c0evS0Oyv8NwzmZS:bnfp4nl)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/194#-:-KmDk9wdDclJ4R1XpC3n:bnfp4nl)*

**Pull request merged**
