### PR TITLE
WIP: antool: fix antool tests

### PR DESCRIPTION
**Pull request by ldorau**
Antool tests depend on the maximum length of a string, because for different values of maximum length of a string, vltrace binary logs are different, so new vltrace binary logs have to be added to the repo.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/332)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
What is the naming scheme for the test files supposed to represent? Why were they renamed?

---

Reviewed 4 of 131 files at r1.
Review status: 3 of 89 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/332#-:-KtO8C6KDdqBH1XCLSYP:b4mkz8p)*

**Comment by ldorau** [comment]
I renamed only match files and binary vltrace log files that are antool's input files.
The naming scheme is following:
```
<name>-<MAX_STR_LEN>-<TEST_NUM>
```
where:
- ```MAX_STR_LEN``` is a maximum length of a string supported by vltrace (set in the '-s' option)
- ```TEST_NUM``` is a number of test case of the test app "test_syscalls.c"

They were renamed, because the antool tests depend on the maximum length of a string too, so vltrace binary logs are different for different values of maximum length of a string. 

Vltace binary logs have to be included in the repo in order to make possible to run antool tests without having vltrace installed and to make them much faster. There are already vltace binary logs included in the repo, but there are too few of them. For example, logs with the maximum length of a string equal 382 were used in tests for the maximum length of a string equal 382 and 126 also. It was a bug., so logs with the maximum length of a string equal 126 have to be added to the repo. 

Vltrace binary logs are generated by vltrace during running antool tests when vltrace is installed in OS and ANTOOL_TESTS is not set or set to different value that 'SAVED' or 'SKIP'.

---

Review status: 4 of 89 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/332#-:-KtQhHwNXV6t4bdtaw38:bxd53tk)*

**Comment by ldorau** [comment]
The code will be moved to another PR.

**Comment by ldorau** [comment]
https://github.com/pmem/pmemfile/pull/340

**Comment by ldorau** [comment]
https://github.com/pmem/pmemfile/pull/341

**Pull request closed without merging**
