### PR TITLE
antool: add support for symlinks

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/379)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
Reviewed 15 of 18 files at r1, 10 of 11 files at r2.
Review status: 24 of 27 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/tools/antool/antool.py, line 449 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/379#-KuzDUoGOziq56cVYvSr:-KuzDUoGOziq56cVYvSs:b-p7o7qd) ([raw file](https://github.com/pmem/pmemfile/blob/c3f7bb9f9cd820a5e068e9a88ba3ec1dc569c70f/src/tools/antool/antool.py#L449)):*
> ```Python
> 
>     parser.add_argument("--slink_os", action='store_true', required=False, help="resolve symlinks in the current OS")
>     parser.add_argument("--slink_file", required=False, help="resolve symlinks saved in the given file")
> ```

Why is symlink support a command line option?

---

*[src/tools/antool/listsyscalls.py, line 200 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/379#-KuzWSuU84kbg6Lidea7:-KuzWSuU84kbg6Lidea8:bsn8pji) ([raw file](https://github.com/pmem/pmemfile/blob/c3f7bb9f9cd820a5e068e9a88ba3ec1dc569c70f/src/tools/antool/listsyscalls.py#L200)):*
> ```Python
> 
>                 if self.slink_file and new_path in self.symlinks:
>                     new_path = self.symlinks[new_path]
> ```

Is the point that if it is already a resolved symlink we just assign it based on its previously resolved value? Maybe add comments here.

---

*[src/tools/antool/listsyscalls.py, line 499 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/379#-KuzWdV5sdfO7pyvZJ9E:-KuzWdV5sdfO7pyvZJ9F:b-ufvlk5) ([raw file](https://github.com/pmem/pmemfile/blob/c3f7bb9f9cd820a5e068e9a88ba3ec1dc569c70f/src/tools/antool/listsyscalls.py#L499)):*
> ```Python
>     # handle_fileat -- helper function of match_fd_with_path() - handles *at syscalls
>     ####################################################################################################################
>     def handle_fileat(self, syscall, arg1, arg2, msg, has_to_be_pmem):
> ```

What does has_to_be_pmem mean/do? Please add a comment.

---

*[tests/antool/test_syscalls.c, line 544 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/379#-KuzYk4M5vymf8PMFEht:-KuzYk4M5vymf8PMFEhu:b-bm43kc) ([raw file](https://github.com/pmem/pmemfile/blob/c3f7bb9f9cd820a5e068e9a88ba3ec1dc569c70f/tests/antool/test_syscalls.c#L544)):*
> ```C
> verify_and_open(const char *dir, const char *pmem, const char *nonp,
> 		char **abspmem_p, char **absnonp_p,
> 		int *dirfd_p, int *fdpmem_p, int *fdnonp_p)
> ```

Could you add comments as to what the variable names represent in the function header? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/379)*

**Comment by ldorau** [comment]
Review status: 16 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/tools/antool/antool.py, line 449 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/379#-KuzDUoGOziq56cVYvSr:-Kv6pyy_8kxuzUb5iL07:bge17o9) ([raw file](https://github.com/pmem/pmemfile/blob/c3f7bb9f9cd820a5e068e9a88ba3ec1dc569c70f/src/tools/antool/antool.py#L449)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why is symlink support a command line option?
</blockquote></details>

I removed the '--slink_os' option and it is always enabled now.
The '--slink_file' option is used to give a file with list of symlinks which existed when the app was running but are no longer valid.

---

*[src/tools/antool/listsyscalls.py, line 200 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/379#-KuzWSuU84kbg6Lidea7:-Kv6s309UWXwxhrDzf3o:b-8ng21h) ([raw file](https://github.com/pmem/pmemfile/blob/c3f7bb9f9cd820a5e068e9a88ba3ec1dc569c70f/src/tools/antool/listsyscalls.py#L200)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Is the point that if it is already a resolved symlink we just assign it based on its previously resolved value? Maybe add comments here.
</blockquote></details>

I added the comment:
```
# if there is a file with symlinks given by the '--slink_file' CLI option
# and the current 'new_path' is saved as a symlink in this file,
# replace it with the target path saved also in this file.
```

---

*[src/tools/antool/listsyscalls.py, line 499 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/379#-KuzWdV5sdfO7pyvZJ9E:-Kv6tdJvnZ0gYIX9x3ds:b-girvck) ([raw file](https://github.com/pmem/pmemfile/blob/c3f7bb9f9cd820a5e068e9a88ba3ec1dc569c70f/src/tools/antool/listsyscalls.py#L499)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

What does has_to_be_pmem mean/do? Please add a comment.
</blockquote></details>

I added the comment :
```
################################################################################################
# handle_fileat -- helper function of match_fd_with_path() - handles *at syscalls
#    syscall        - current syscall
#    arg1           - number of the argument with a file descriptor
#    arg2           - number of the argument with a path
#    msg            - message to be printed out built so far
#    has_to_be_pmem - if set, force the new path to be pmem (in case of SyS_symlinkat)
################################################################################################
```

---

*[tests/antool/test_syscalls.c, line 544 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/379#-KuzYk4M5vymf8PMFEht:-Kv71DxCoTrxCy_5zEjt:b-up7zr0) ([raw file](https://github.com/pmem/pmemfile/blob/c3f7bb9f9cd820a5e068e9a88ba3ec1dc569c70f/tests/antool/test_syscalls.c#L544)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Could you add comments as to what the variable names represent in the function header? 
</blockquote></details>

I added a comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/379)*

**Comment by ldorau** [comment]
Review status: 16 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/tools/antool/antool.py, line 449 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/379#-KuzDUoGOziq56cVYvSr:-Kv7BmILW9Uuk1H-wz7q:bmvlzpd) ([raw file](https://github.com/pmem/pmemfile/blob/c3f7bb9f9cd820a5e068e9a88ba3ec1dc569c70f/src/tools/antool/antool.py#L449)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I removed the '--slink_os' option and it is always enabled now.
The '--slink_file' option is used to give a file with list of symlinks which existed when the app was running but are no longer valid.

</blockquote></details>

So symlink support is always enabled now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/379)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: 16 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/379#-:-KvCk3w2VuXfYbGhbiMZ:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/379)*

**Pull request merged**
