### PR TITLE
preload: handle mknod and mknodat

### PR DESCRIPTION
**Pull request by marcinslusarz**
Ref: pmem/pmemfile#205

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/210)

### CODE REVIEW

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210#-:-KmzXzd3KJHjFaB0Vzkd:bnfp4nl)*

**Comment by GBuella** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/libpmemfile/preload.c, line 1288 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/210#-Kmzou1W-0Nz3wB1i2SG:-Kmzou1W-0Nz3wB1i2SH:b-xzfo78) ([raw file](https://github.com/pmem/pmemfile/blob/cad6d5217d5df2b348db7b353bf40b6c2dd45aae/src/libpmemfile/preload.c#L1288)):*
> ```C
> 	    where.at.pmem_fda.file, where.path, (mode_t)mode, (dev_t)dev);
> 
> 	log_write("pmemfile_mknodat(%p, \"%s\", 0%lo, %ld) = %ld",
> ```

Would we ever need this section of code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210)*

**Comment by marcinslusarz** [comment]
*[src/libpmemfile/preload.c, line 1288 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/210#-Kmzou1W-0Nz3wB1i2SG:-KmzqOE0AD-9b7TFq6UN:b-8e5434) ([raw file](https://github.com/pmem/pmemfile/blob/cad6d5217d5df2b348db7b353bf40b6c2dd45aae/src/libpmemfile/preload.c#L1288)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Would we ever need this section of code?
</blockquote></details>

I have an idea how to handle special file types in libpmemfile but it requires some support from libpmemfile-posix.

The idea is to create real special files outside of pmemfile pool (possibly at mount point) and link to them from libpmemfile-posix pool.
Libpmemfile-posix would expose mknodat function with additional argument specifying the path to the real file. It would be possible to open such file, but all normal file operations would fail (with an exception of close). The only one which would work is pmemfile_node_stat - after each pmemfile_open libpmemfile would call pmemfile_node_stat and if it's special file it would call open on path obtained from it.

So yeah, this section of code may be needed later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile/preload.c, line 1288 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/210#-Kmzou1W-0Nz3wB1i2SG:-Kn01Ge9snKsHTvpyfAY:b-pkqxue) ([raw file](https://github.com/pmem/pmemfile/blob/cad6d5217d5df2b348db7b353bf40b6c2dd45aae/src/libpmemfile/preload.c#L1288)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I have an idea how to handle special file types in libpmemfile but it requires some support from libpmemfile-posix.

The idea is to create real special files outside of pmemfile pool (possibly at mount point) and link to them from libpmemfile-posix pool.
Libpmemfile-posix would expose mknodat function with additional argument specifying the path to the real file. It would be possible to open such file, but all normal file operations would fail (with an exception of close). The only one which would work is pmemfile_node_stat - after each pmemfile_open libpmemfile would call pmemfile_node_stat and if it's special file it would call open on path obtained from it.

So yeah, this section of code may be needed later.

</blockquote></details>

I still think the `#if 1` part is ugly.
I think there should be a stub `pmemfile_mknodat` implementation in libpmemfile-posix, and there should be no need for such conditional compilation here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210)*

**Comment by marcinslusarz** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile/preload.c, line 1288 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/210#-Kmzou1W-0Nz3wB1i2SG:-Kn5CtpauIPcJKG4waLQ:bjko98z) ([raw file](https://github.com/pmem/pmemfile/blob/cad6d5217d5df2b348db7b353bf40b6c2dd45aae/src/libpmemfile/preload.c#L1288)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

I still think the `#if 1` part is ugly.
I think there should be a stub `pmemfile_mknodat` implementation in libpmemfile-posix, and there should be no need for such conditional compilation here.
</blockquote></details>

Fair enough. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210)*

**Comment by sarahjelinek** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/libpmemfile/preload.c, line 1288 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/210#-Kmzou1W-0Nz3wB1i2SG:-Kn5jrVpv0rkWiyGY0Y3:b-rts8rb) ([raw file](https://github.com/pmem/pmemfile/blob/cad6d5217d5df2b348db7b353bf40b6c2dd45aae/src/libpmemfile/preload.c#L1288)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Fair enough. Done.
</blockquote></details>

mknod() is an explicit non-requirement for pmemfile V1.0. It's also shown as not supported in the libpmemfile manpage and not in the libpmemfile-posix manpage. Please modify man pages to include support for this for creating regular files only, correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210)*

**Comment by sarahjelinek** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile/preload.c, line 1288 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/210#-Kmzou1W-0Nz3wB1i2SG:-Kn6bF4rMQTPuLqCQxHk:b87maao) ([raw file](https://github.com/pmem/pmemfile/blob/cad6d5217d5df2b348db7b353bf40b6c2dd45aae/src/libpmemfile/preload.c#L1288)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

mknod() is an explicit non-requirement for pmemfile V1.0. It's also shown as not supported in the libpmemfile manpage and not in the libpmemfile-posix manpage. Please modify man pages to include support for this for creating regular files only, correct?
</blockquote></details>

You can create a new pull request for the man page updates if you don;t want to include it in this one. Just let me know your plans.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210)*

**Comment by sarahjelinek** [comment]
Reviewed 1 of 2 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210)*

**Comment by marcinslusarz** [comment]
Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/libpmemfile/preload.c, line 1288 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/210#-Kmzou1W-0Nz3wB1i2SG:-Kn9G4kuowhzk9o0Ldcf:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/cad6d5217d5df2b348db7b353bf40b6c2dd45aae/src/libpmemfile/preload.c#L1288)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

You can create a new pull request for the man page updates if you don;t want to include it in this one. Just let me know your plans.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210)*

**Comment by sarahjelinek** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210#-:-Kn9o1qWNbDM4gkcs5RY:bnfp4nl)*

**Comment by GBuella** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210#-:-Kn9rPUimAEXJpewRrRK:bnfp4nl)*

**Comment by krzycz** [comment]
Reviewed 5 of 5 files at r2, 5 of 5 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/210)*

**Pull request merged**
