### PR TITLE
pjdfstest integration

### PR DESCRIPTION
**Pull request by marcinslusarz**
Unfortunately we can't enable it on Travis - process switching is too slow :(.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/335)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[utils/docker/pjdfstest/test.sh, line 77 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/335#-KtjxVb8Ul2Npf8IrE7i:-KtjxVb8Ul2Npf8IrE7j:b3kre) ([raw file](https://github.com/pmem/pmemfile/blob/7ac7f14a73324ceee6e47a81d6ca764af1a1b63a/utils/docker/pjdfstest/test.sh#L77)):*
> ```Shell
> mkfs.pmemfile ${PMEMFILE_POOL_FILE} ${PMEMFILE_POOL_SIZE}
> pmemfile-mount ${PMEMFILE_POOL_FILE} ${PMEMFILE_MOUNT_POINT}
> #export PMEMFILE_POOLS=${PMEMFILE_MOUNT_POINT}:${PMEMFILE_POOL_FILE}
> ```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/335)*

**Comment by marcinslusarz** [comment]
*[utils/docker/pjdfstest/test.sh, line 77 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/335#-KtjxVb8Ul2Npf8IrE7i:-Ktkpj9DQcG5nYafA_a2:bss4a2b) ([raw file](https://github.com/pmem/pmemfile/blob/7ac7f14a73324ceee6e47a81d6ca764af1a1b63a/utils/docker/pjdfstest/test.sh#L77)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/335)*

**Comment by krzycz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/335)*

**Comment by krzycz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/335#-:-KtkzWS2q1p9dRUC91mr:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Review status: 9 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[utils/docker/images/install-pjdfstest.sh, line 40 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/335#-KtliqFYSxFqnW1AtjRF:-KtliqFYSxFqnW1AtjRG:b41fn4o) ([raw file](https://github.com/pmem/pmemfile/blob/3413d081ef8ffdd283d8db224d6c5f20aece7179/utils/docker/images/install-pjdfstest.sh#L40)):*
> ```Shell
> 
> cd $HOME
> curl -L -o pjdfstest.zip https://github.com/pjd/pjdfstest/archive/${commitid}.zip
> ```

What happens if the 'curl' command fails? Shouldn't you check for the exit code here? If there is a proxy failure or something else that gets in the way of downloading this image we should fail. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/335)*

**Comment by marcinslusarz** [comment]
*[utils/docker/images/install-pjdfstest.sh, line 40 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/335#-KtliqFYSxFqnW1AtjRF:-KtlmCrrElo13Vy0SSAy:b3tvi8) ([raw file](https://github.com/pmem/pmemfile/blob/3413d081ef8ffdd283d8db224d6c5f20aece7179/utils/docker/images/install-pjdfstest.sh#L40)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

What happens if the 'curl' command fails? Shouldn't you check for the exit code here? If there is a proxy failure or something else that gets in the way of downloading this image we should fail. 
</blockquote></details>

I curl fails the whole script fails. "-e" in the first line (bash -ex) of the script assures that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/335)*

**Comment by sarahjelinek** [comment]
Reviewed 4 of 16 files at r1, 1 of 2 files at r2.
Review status: 9 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[utils/docker/images/install-pjdfstest.sh, line 40 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/335#-KtliqFYSxFqnW1AtjRF:-KtlnLlvJTtw82UFgY1w:bsb1342) ([raw file](https://github.com/pmem/pmemfile/blob/3413d081ef8ffdd283d8db224d6c5f20aece7179/utils/docker/images/install-pjdfstest.sh#L40)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I curl fails the whole script fails. "-e" in the first line (bash -ex) of the script assures that.
</blockquote></details>

Oh, missed that :-). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/335)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: 9 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/335#-:-KtlnfBOmpEqeyDjhgH6:bnfp4nl)*

**Pull request merged**
