### PR TITLE
preload: various fixes

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/216)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libpmemfile/path_resolve.c, line 365 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/216#-KnBglcjdJ-56ZOfMGc5:-KnBglckH6_Wp-TA9jtv:be0jcx2) ([raw file](https://github.com/pmem/pmemfile/blob/9d45111a79a059bc6781e0b79e1f6c765a49acb0/src/libpmemfile/path_resolve.c#L365)):*
> ```C
> 				&resolved, &end, &size, &is_last_component);
> 			num_symlinks++;
> 			if (num_symlinks > 40) {
> ```

Why 40?

---

*[src/libpmemfile/preload.c, line 372 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/216#-KnBmVNQINOyiHwCVVQn:-KnBmVNR5nTMolqgeMpB:bh8t8y0) ([raw file](https://github.com/pmem/pmemfile/blob/9d45111a79a059bc6781e0b79e1f6c765a49acb0/src/libpmemfile/preload.c#L372)):*
> ```C
> 	resolve_path(at0, (const char *)arg0, &where_old, RESOLVE_LAST_SLINK);
> 	resolve_path(at1, (const char *)arg1, &where_new,
> 			NO_RESOLVE_LAST_SLINK);
> ```

I don't understand why you made this change. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/216)*

**Comment by marcinslusarz** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libpmemfile/path_resolve.c, line 365 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/216#-KnBglcjdJ-56ZOfMGc5:-KnEFw_NUNR64N3i2UoW:bd33uka) ([raw file](https://github.com/pmem/pmemfile/blob/9d45111a79a059bc6781e0b79e1f6c765a49acb0/src/libpmemfile/path_resolve.c#L365)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why 40?
</blockquote></details>

Sort of arbitrary number, but not really ;) - it's the same value as used by the Linux kernel. See "Step 2" in http://man7.org/linux/man-pages/man7/path_resolution.7.html. We also use the same value in libpmemfile-posix.

---

*[src/libpmemfile/preload.c, line 372 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/216#-KnBmVNQINOyiHwCVVQn:-KnEGlYgzl5s6vcDxyBc:b30fst9) ([raw file](https://github.com/pmem/pmemfile/blob/9d45111a79a059bc6781e0b79e1f6c765a49acb0/src/libpmemfile/preload.c#L372)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

I don't understand why you made this change. 
</blockquote></details>

Resolving last component of the destination path fails if it doesn't exist. With "link" it's a common use case. And even when last component is a symlink we should NOT follow it. That's how link syscall works.

This PR is best reviewed patch by patch. Added test case failed (with ENOENT) without this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/216)*

**Comment by GBuella** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libpmemfile/path_resolve.c, line 365 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/216#-KnBglcjdJ-56ZOfMGc5:-KnEYpZV2hUrp4zw77e-:b-7w41v0) ([raw file](https://github.com/pmem/pmemfile/blob/9d45111a79a059bc6781e0b79e1f6c765a49acb0/src/libpmemfile/path_resolve.c#L365)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Sort of arbitrary number, but not really ;) - it's the same value as used by the Linux kernel. See "Step 2" in http://man7.org/linux/man-pages/man7/path_resolution.7.html. We also use the same value in libpmemfile-posix.
</blockquote></details>

I see, just add a comment here explaining the same thing please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/216#-:-KnEZ-_e73-rjp6-R8EI:bnfp4nl)*

**Comment by marcinslusarz** [comment]
*[src/libpmemfile/path_resolve.c, line 365 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/216#-KnBglcjdJ-56ZOfMGc5:-KnEkXy4-Rc9bQcicfEj:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/9d45111a79a059bc6781e0b79e1f6c765a49acb0/src/libpmemfile/path_resolve.c#L365)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

I see, just add a comment here explaining the same thing please.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/216)*

**Comment by GBuella** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/216)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/216#-:-KnGgmWgcGSd4sOvq9LI:bnfp4nl)*

**Pull request merged**
