### PR TITLE
antool: add codecov for python to docker images

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/284)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Please add those changes to all Dockerfiles and explain in the commit message why we need mercurial.

**Comment by GBuella** [comment]
So this just installs python codecov, but does not use it yet, right?

**Comment by ldorau** [comment]
> So this just installs python codecov, but does not use it yet, right?
>
Right

**Comment by ldorau** [comment]
> why we need mercurial.
>
```
+ ../codecov

      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.9

==> Detecting CI provider
    Travis Detected
==> Preparing upload
/bin/sh: 1: hg: not found
    Error running `cd /pmemfile/build && hg locate`: None
/bin/sh: 1: hg: not found
    Error running `hg locate`: None
```

**Comment by ldorau** [comment]
I removed mercurial

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/284#-:-Kq8S9tez4PX_I-wcs9J:bnfp4nl)*

**Comment by GBuella** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/284#-:-Kq8VMzelOViI1DatDk1:bnfp4nl)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/284#-:-Kq9cLmkvjmdkN6eSy7G:bnfp4nl)*

**Pull request merged**
