### PR TITLE
antool: more minor fixes

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/353)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/353)*

**Comment by sarahjelinek** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/tools/antool/listsyscalls.py, line 410 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/353#-KtwkmTOcGQuBAsBIZcK:-KtwkmTOcGQuBAsBIZcL:bds45nq) ([raw file](https://github.com/pmem/pmemfile/blob/09eff9612bf3e47a0ca54c472f06a367895500a7/src/tools/antool/listsyscalls.py#L410)):*
> ```Python
>             # the SyS_flock syscall is not supported YET
>             if syscall.name == "flock":
>                 return RESULT_UNSUPPORTED_YET
> ```

We don't have flock() listed as supported at all. Did this change? 

---

*[src/tools/antool/listsyscalls.py, line 625 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/353#-KtwmfOh8smWJwWvZ_4c:-KtwmfOh8smWJwWvZ_4d:b-sbmvdv) ([raw file](https://github.com/pmem/pmemfile/blob/09eff9612bf3e47a0ca54c472f06a367895500a7/src/tools/antool/listsyscalls.py#L625)):*
> ```Python
> 
>                 if fd_out != -1:  # pragma: no cover
>                     self.log_anls.warning("Unknown fd : {0:d}".format(fd_in))
> ```

I am a little confused by this 'no cover'. And it could be that it's because I don't completely understand the coverage utility but why would this piece of code never be executed and excluded from coverage?

---

*[src/tools/antool/listsyscalls.py, line 712 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/353#-Ktwn3bQwNiQg1OxCb7j:-Ktwn3bQwNiQg1OxCb7k:bqqh5h5) ([raw file](https://github.com/pmem/pmemfile/blob/09eff9612bf3e47a0ca54c472f06a367895500a7/src/tools/antool/listsyscalls.py#L712)):*
> ```Python
>                             msg += " ({0:d})".format(fd)
>                         else:  # pragma: no cover
>                             msg += " (0x{0:016X})".format(fd)
> ```

Why no coverage here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/353)*

**Comment by ldorau** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/tools/antool/listsyscalls.py, line 410 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/353#-KtwkmTOcGQuBAsBIZcK:-Ku3EB5L7LY8zSsj9wde:b3e5gst) ([raw file](https://github.com/pmem/pmemfile/blob/09eff9612bf3e47a0ca54c472f06a367895500a7/src/tools/antool/listsyscalls.py#L410)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

We don't have flock() listed as supported at all. Did this change? 
</blockquote></details>

SyS_flock is listed as "unsupported yet" now:
https://github.com/pmem/pmemfile/blob/master/STATUS.md

I cannot remember if its status was changed.

---

*[src/tools/antool/listsyscalls.py, line 625 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/353#-KtwmfOh8smWJwWvZ_4c:-Ku41mpaY0VxpHRDrvi-:bgg8ske) ([raw file](https://github.com/pmem/pmemfile/blob/09eff9612bf3e47a0ca54c472f06a367895500a7/src/tools/antool/listsyscalls.py#L625)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

I am a little confused by this 'no cover'. And it could be that it's because I don't completely understand the coverage utility but why would this piece of code never be executed and excluded from coverage?
</blockquote></details>

OK, it will be covered by a fault-injection test. I am removing this commit.

---

*[src/tools/antool/listsyscalls.py, line 712 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/353#-Ktwn3bQwNiQg1OxCb7j:-Ku424lKFXpe_kvzpQHT:bgg8ske) ([raw file](https://github.com/pmem/pmemfile/blob/09eff9612bf3e47a0ca54c472f06a367895500a7/src/tools/antool/listsyscalls.py#L712)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why no coverage here?
</blockquote></details>

OK, it will be covered by a fault-injection test. I am removing this commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/353)*

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/353)*

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/353)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/353#-:-KuM2RYBCvsJwOOpDl6t:bnfp4nl)*

**Pull request merged**
