### PR TITLE
posix: fault injection extension

### PR DESCRIPTION
**Pull request by mramotowski**
Extension for fault injections tests

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/255)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/255)*

**Comment by marcinslusarz** [comment]
There's no such word as "exten"/"extens". I'd suggest to replace this commit message with "tests: test more copy_cred failure paths" 

---

Reviewed 4 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[tests/posix/dirs/dirs.cpp, line 966 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KpFQ9eM2eXiuCcN17aA:-KpFQ9eM2eXiuCcN17aB:blwyflf) ([raw file](https://github.com/pmem/pmemfile/blob/ba7a1ca01e12dfe9c4fdc2a38769552938e65198/tests/posix/dirs/dirs.cpp#L966)):*
> ```cpp
> 	ASSERT_EQ(pmemfile_rmdir(pfp, "/dir1"), -1);
> 	EXPECT_EQ(errno, ENOMEM);
> #endif
> ```

This doesn't belong to "file_renames_in_same_tree" test.

---

*[tests/posix/dirs/dirs.cpp, line 1829 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KpFQUOI8MCQgt1wZrh_:-KpFQUOI8MCQgt1wZrha:b-z0yex4) ([raw file](https://github.com/pmem/pmemfile/blob/ba7a1ca01e12dfe9c4fdc2a38769552938e65198/tests/posix/dirs/dirs.cpp#L1829)):*
> ```cpp
> 		  -1);
> 	EXPECT_EQ(errno, ENOMEM);
> #endif
> ```

Doesn't belong to O_PATH test.

---

*[tests/posix/dirs/dirs.cpp, line 1864 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KpFQZUKDxQJWcgvwpH6:-KpFQZUKDxQJWcgvwpH7:bs4q9op) ([raw file](https://github.com/pmem/pmemfile/blob/ba7a1ca01e12dfe9c4fdc2a38769552938e65198/tests/posix/dirs/dirs.cpp#L1864)):*
> ```cpp
> 	ASSERT_EQ(pmemfile_faccessat(pfp, dir, "file", PMEMFILE_W_OK, 0), -1);
> 	EXPECT_EQ(errno, ENOMEM);
> #endif
> ```

Ditto.

---

*[tests/posix/permissions/permissions.cpp, line 913 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KpFRLG84cSjc3z6HHYl:-KpFRLG9XiYhtGZ2CSQ2:bp3ky4z) ([raw file](https://github.com/pmem/pmemfile/blob/ba7a1ca01e12dfe9c4fdc2a38769552938e65198/tests/posix/permissions/permissions.cpp#L913)):*
> ```cpp
> 	ASSERT_EQ(pmemfile_rename(pfp, "/dir_-wx/aaa", "/aaa"), -1);
> 	EXPECT_EQ(errno, ENOMEM);
> #endif
> ```

Please move this to dirs/dirs.cpp/file_renames. This test tests stuff related to permissions.

---

*[tests/posix/symlinks/symlinks.cpp, line 639 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KpFSGZNxLpG_GdCwtw8:-KpFSGZNxLpG_GdCwtw9:bhnjqcg) ([raw file](https://github.com/pmem/pmemfile/blob/ba7a1ca01e12dfe9c4fdc2a38769552938e65198/tests/posix/symlinks/symlinks.cpp#L639)):*
> ```cpp
> 	ASSERT_EQ(pmemfile_symlink(pfp, "../file", "/dir/symlink"), -1);
> 	EXPECT_EQ(errno, ENOMEM);
> #endif
> ```

Doesn't belong here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/255#-:-KpFScA2UQ51Xas8njSW:b-kl0u8o)*

**Comment by marcinslusarz** [comment]
Please make sure tests pass on your machine. One of the tests has a flaw that it prints a lot of data when it fails, which makes Travis unhappy.

**Comment by mramotowski** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[tests/posix/basic/basic.cpp, line 472 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqWYxo1VNypXpb1C24G:-KqWYxo2bwS6CFGxOvZk:b-b1vtwo) ([raw file](https://github.com/pmem/pmemfile/blob/3a62623f330f46b2fe337483338616a7919fa50d/tests/posix/basic/basic.cpp#L472)):*
> create(pfp, "/fileXXX", 0644), nullptr);

---

*[tests/posix/dirs/dirs.cpp, line 966 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KpFQ9eM2eXiuCcN17aA:-KqbSP9oyCI2eVZ9mVju:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/ba7a1ca01e12dfe9c4fdc2a38769552938e65198/tests/posix/dirs/dirs.cpp#L966)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

This doesn't belong to "file_renames_in_same_tree" test.
</blockquote></details>

Done.

---

*[tests/posix/dirs/dirs.cpp, line 1829 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KpFQUOI8MCQgt1wZrh_:-KqbSO7T2Ox_LT3zvBHa:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/ba7a1ca01e12dfe9c4fdc2a38769552938e65198/tests/posix/dirs/dirs.cpp#L1829)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Doesn't belong to O_PATH test.
</blockquote></details>

Done.

---

*[tests/posix/dirs/dirs.cpp, line 1864 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KpFQZUKDxQJWcgvwpH6:-KqbSNNhXm8tFFH2K3h0:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/ba7a1ca01e12dfe9c4fdc2a38769552938e65198/tests/posix/dirs/dirs.cpp#L1864)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.

---

*[tests/posix/permissions/permissions.cpp, line 913 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KpFRLG84cSjc3z6HHYl:-KqbSMmCfuZ3KVtVIyiB:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/ba7a1ca01e12dfe9c4fdc2a38769552938e65198/tests/posix/permissions/permissions.cpp#L913)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please move this to dirs/dirs.cpp/file_renames. This test tests stuff related to permissions.
</blockquote></details>

Done.

---

*[tests/posix/symlinks/symlinks.cpp, line 639 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KpFSGZNxLpG_GdCwtw8:-KqbSLEq1ULoE5ypd2XV:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/ba7a1ca01e12dfe9c4fdc2a38769552938e65198/tests/posix/symlinks/symlinks.cpp#L639)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Doesn't belong here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/255)*

**Comment by marcinslusarz** [comment]
Reviewed 4 of 8 files at r3.
Review status: 4 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[tests/posix/basic/basic.cpp, line 472 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqWYxo1VNypXpb1C24G:-KqiFE1ibSRp2SwAZRxR:b3kre) ([raw file](https://github.com/pmem/pmemfile/blob/3a62623f330f46b2fe337483338616a7919fa50d/tests/posix/basic/basic.cpp#L472)):*
<details><summary><i>Previously, mramotowski wrote…</i></summary><blockquote>

> create(pfp, "/fileXXX", 0644), nullptr);
</blockquote></details>

?

---

*[tests/posix/openp/openp.cpp, line 193 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiDSKYHrRgz4E1fnV0:-KqiDSKZ0jgDBV4ZYMOA:bskq74i) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/openp/openp.cpp#L193)):*
> ```cpp
> 	char path[PMEMFILE_PATH_MAX];
> 	strncpy(path, "dir", PMEMFILE_PATH_MAX);
> 	path[PMEMFILE_PATH_MAX - 1] = 0;
> ```

You don't need this variable. Just use "dir" in pmemfile_open_parent call.

---

*[tests/posix/openp/openp.cpp, line 197 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiFSXXrKLz1AVsASwG:-KqiFSXXrKLz1AVsASwH:b-sg6al7) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/openp/openp.cpp#L197)):*
> ```cpp
> 	pmemfile_inject_fault_at(PF_MALLOC, 1, "copy_cred");
> 	errno = 0;
> 	pmemfile_open_parent(pfp, PMEMFILE_AT_CWD, path, PMEMFILE_PATH_MAX,
> ```

What about the return value?

---

*[tests/posix/openp/openp.cpp, line 198 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiFe0_-4_XdH4x5na7:-KqiFe0_-4_XdH4x5na8:b-ehuy5r) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/openp/openp.cpp#L198)):*
> ```cpp
> 	errno = 0;
> 	pmemfile_open_parent(pfp, PMEMFILE_AT_CWD, path, PMEMFILE_PATH_MAX,
> 			     0 ? PMEMFILE_OPEN_PARENT_STOP_AT_ROOT : 0);
> ```

That's equivalent to "0".

---

*[tests/posix/permissions/permissions.cpp, line 1716 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiFzeWMqcDijQI-JCU:-KqiFzeWMqcDijQI-JCV:bz4pyz3) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/permissions/permissions.cpp#L1716)):*
> ```cpp
> 	EXPECT_TRUE(_test_facc(pfp, dir, "file_-w-r---w-", PMEMFILE_F_OK, 0,
> 			       ENOMEM));
> 	EXPECT_EQ(errno, ENOMEM);
> ```

Already checked by _test_facc one line above.

---

*[tests/posix/rw/rw.cpp, line 710 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiELYpDz20AhqhO554:-KqiELYpDz20AhqhO555:bab7sji) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/rw/rw.cpp#L710)):*
> ```cpp
> 
> 	r = pmemfile_truncate(pfp, "/file1", large + 4);
> ```

looks like accidental change

---

*[tests/posix/stat/stat.cpp, line 297 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiEkZs917zp-4_hm4w:-KqiEkZtgvHbaNUZ26bj:b-a8wxid) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/stat/stat.cpp#L297)):*
> ```cpp
> 	EXPECT_EQ(test_fstatat(pfp, dir, "../file2",
> 			       PMEMFILE_AT_SYMLINK_NOFOLLOW, 0120777, 1, 10, 1,
> 			       0),
> ```

You don't need test_fstatat. Just call pmemfile_fstatat directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/255)*

**Comment by mramotowski** [comment]
Review status: 4 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[tests/posix/basic/basic.cpp, line 472 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqWYxo1VNypXpb1C24G:-KqvFSZGSo40ZljsyJ_U:b5yygmf) ([raw file](https://github.com/pmem/pmemfile/blob/3a62623f330f46b2fe337483338616a7919fa50d/tests/posix/basic/basic.cpp#L472)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

?
</blockquote></details>

missclick

---

*[tests/posix/openp/openp.cpp, line 193 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiDSKYHrRgz4E1fnV0:-KqvSqdHCveAzEZYTpKR:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/openp/openp.cpp#L193)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

You don't need this variable. Just use "dir" in pmemfile_open_parent call.
</blockquote></details>

Done.

---

*[tests/posix/openp/openp.cpp, line 197 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiFSXXrKLz1AVsASwG:-KqvStLjOBcGs5GiSAMK:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/openp/openp.cpp#L197)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

What about the return value?
</blockquote></details>

Done.

---

*[tests/posix/openp/openp.cpp, line 198 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiFe0_-4_XdH4x5na7:-KqvSu2-QFAIF7Tnd0Vm:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/openp/openp.cpp#L198)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

That's equivalent to "0".
</blockquote></details>

Done.

---

*[tests/posix/permissions/permissions.cpp, line 1716 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiFzeWMqcDijQI-JCU:-KqvAFc2M32P-WXBqyKg:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/permissions/permissions.cpp#L1716)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Already checked by _test_facc one line above.
</blockquote></details>

Done.

---

*[tests/posix/rw/rw.cpp, line 710 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiELYpDz20AhqhO554:-KqvAslWBYk664tCDojB:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/rw/rw.cpp#L710)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

looks like accidental change
</blockquote></details>

Done.

---

*[tests/posix/stat/stat.cpp, line 297 at r3](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqiEkZs917zp-4_hm4w:-KqvCRWBUp8ZI2IWilKM:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/eefdea8feb87e11520ab373d55103ed39b0676d5/tests/posix/stat/stat.cpp#L297)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

You don't need test_fstatat. Just call pmemfile_fstatat directly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/255)*

**Comment by marcinslusarz** [comment]
Reviewed 1 of 8 files at r3, 3 of 4 files at r4.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/posix/openp/openp.cpp, line 193 at r4](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqxsT_3zBNv0AaTT7Ba:-KqxsT_4UvpPaonHeCXf:b-lfmiik) ([raw file](https://github.com/pmem/pmemfile/blob/a3be2d603b6145c332f2bac153df24beaa1fec4b/tests/posix/openp/openp.cpp#L193)):*
> ```cpp
> 	pmemfile_inject_fault_at(PF_MALLOC, 1, "copy_cred");
> 	errno = 0;
> 	ASSERT_EQ(pmemfile_open_parent(pfp, PMEMFILE_AT_CWD, (char *)"dir",
> ```

Ouch, I was wrong. pmemfile_open_parent modifies "path" argument, so you need local variable. Just use strcpy please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/255)*

**Comment by mramotowski** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/posix/openp/openp.cpp, line 193 at r4](https://reviewable.io:443/reviews/pmem/pmemfile/255#-KqxsT_3zBNv0AaTT7Ba:-Kr0WqDeIcz2VTa7_4Aw:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/a3be2d603b6145c332f2bac153df24beaa1fec4b/tests/posix/openp/openp.cpp#L193)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Ouch, I was wrong. pmemfile_open_parent modifies "path" argument, so you need local variable. Just use strcpy please.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/255)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/255#-:-Kr1OxUyDArTCBKQfmiH:bnfp4nl)*

**Comment by GBuella** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/255#-:-Kr25XHLzsFd91jvWuzw:bnfp4nl)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 4 of 8 files at r3, 3 of 4 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/255#-:-Kr5bFZVkkKeEGcYCtY0:bnfp4nl)*

**Pull request merged**
