### PR TITLE
antool: add more tests

### PR DESCRIPTION
**Pull request by ldorau**
This PR depends on PR https://github.com/pmem/pmemfile/pull/346, which has to be merged first.
Only 2 top-last commits actually belongs to this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/341)

### CODE REVIEW

**Comment by sarahjelinek** [comment]
Reviewed 99 of 125 files at r1, 4 of 59 files at r2.
Review status: 57 of 133 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/tools/antool/antool.py, line 313 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-Ktmi4G54NJOdFm1FNeG:-Ktmi4G6Xpyp4BPHMJP_:b-8rju71) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/src/tools/antool/antool.py#L313)):*
> ```Python
>             # read header = command line
>             data_size, argc = read_fmt_data(fh, 'ii')
>             data_size -= sizei
> ```

Why do you decrement data_size by sizei when you have read 'ii'? Which is 2 * sizei? A comment would be helpful here.

---

*[src/tools/antool/antool.py, line 348 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-KtmjKx16atXP-qsRSQ4:-KtmjKx16atXP-qsRSQ5:b-u9ujj9) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/src/tools/antool/antool.py#L348)):*
> ```Python
>                 # read data from the file
>                 data_size, info_all, pid_tid, sc_id, timestamp = read_fmt_data(fh, 'IIQQQ')
>                 data_size -= sizeIQQQ
> ```

data_size -= sizeIQQQ when you have read 'IIQQQ'? 

---

*[tests/antool/output-err-1531-12.log.match, line 0 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-KtmoipPBqoMyQbWufpK:-KtmoipPBqoMyQbWufpL:b-xztrhe) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/tests/antool/output-err-1531-12.log.match#L0)):*
Why are some of these empty files?

---

*[tests/antool/test-antool.sh, line 47 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-KtmqvtfcsyXAK7FISzt:-KtmqvtgTvwH65Z5vNH0:bfp3tc6) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/tests/antool/test-antool.sh#L47)):*
> ```Shell
> if [ "$4" == "" ]; then
> 	echo "ERROR($NAME): not enough arguments"
> 	echo "Usage: $0 [-f] <path-to-vltrace> <max-string-length> <test-app> <test-number>"
> ```

What is max-string-length used for and how would a user know what this length should be if they ran this by hand?

---

*[tests/antool/test-fi.sh, line 34 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-Ktmp3zlUoxkKNKxEbsc:-Ktmp3zlUoxkKNKxEbsd:bkiokp3) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/tests/antool/test-fi.sh#L34)):*
> ```Shell
> #
> #
> # test-others.sh -- other test for analyzing tool
> ```

Why is this name test-fi.sh when internally you call it test-others.sh?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/341)*

**Comment by ldorau** [comment]
Review status: 57 of 133 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/tools/antool/antool.py, line 313 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-Ktmi4G54NJOdFm1FNeG:-KtooLGe6KupWiM_vyxi:b-l2l6v0) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/src/tools/antool/antool.py#L313)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why do you decrement data_size by sizei when you have read 'ii'? Which is 2 * sizei? A comment would be helpful here.
</blockquote></details>

A comment added:
```
# subtract size of argc only, because 'data_size' does not include its own size
```

---

*[src/tools/antool/antool.py, line 348 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-KtmjKx16atXP-qsRSQ4:-KtooU50MftYuq_4EKrh:b-th559) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/src/tools/antool/antool.py#L348)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

data_size -= sizeIQQQ when you have read 'IIQQQ'? 
</blockquote></details>

A comment added:
```
# subtract size of all read fields except of 'data_size' itself,
# because 'data_size' does not include its own size
```

---

*[tests/antool/output-err-1531-12.log.match, line  at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-KtmoipPBqoMyQbWufpK:-Ktoom7xoLzJYroI4fM8:b-p0n8y2) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/tests/antool/output-err-1531-12.log.match#L)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why are some of these empty files?
</blockquote></details>

Because there should be no stderr output for these tests.

---

*[tests/antool/test-antool.sh, line 47 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-KtmqvtfcsyXAK7FISzt:-Ktop6wmI9yxjcDDlda1:bjnozap) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/tests/antool/test-antool.sh#L47)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

What is max-string-length used for and how would a user know what this length should be if they ran this by hand?
</blockquote></details>

This is a parameter of vltrace. It is described in the manual and the help message of vltrace. I added a comment here.
This changed was moved to a separate PR:  https://github.com/pmem/pmemfile/pull/346 which this PR depends on now.

---

*[tests/antool/test-fi.sh, line 34 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-Ktmp3zlUoxkKNKxEbsc:-KtoormZkTw6ppk2x22t:b-x7jgz1) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/tests/antool/test-fi.sh#L34)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

Why is this name test-fi.sh when internally you call it test-others.sh?
</blockquote></details>

Just a mistake - it was the previous, old name. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/341)*

**Comment by ldorau** [comment]
This PR depends on PR https://github.com/pmem/pmemfile/pull/346, which has to be merged first.
Only 2 top-last commits actually belongs to this PR.

**Comment by ldorau** [comment]
Review status: 51 of 75 files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/antool/output-err-1531-12.log.match, line  at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-KtmoipPBqoMyQbWufpK:-KtpGOc1bz6YqRNXd3P0:b-8ppmzb) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/tests/antool/output-err-1531-12.log.match#L)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Because there should be no stderr output for these tests.
</blockquote></details>

The files were moved to PR https://github.com/pmem/pmemfile/pull/346 to the commit https://github.com/pmem/pmemfile/pull/346/commits/04d422e4822f11edaa535452dfb21b1a159de6cb

---

*[tests/antool/test-antool.sh, line 47 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-KtmqvtfcsyXAK7FISzt:-KtpGfKSdQeknFvrhaAD:bmisg9c) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/tests/antool/test-antool.sh#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This is a parameter of vltrace. It is described in the manual and the help message of vltrace. I added a comment here.
This changed was moved to a separate PR:  https://github.com/pmem/pmemfile/pull/346 which this PR depends on now.
</blockquote></details>

... to the commit https://github.com/pmem/pmemfile/pull/346/commits/052414efb38c45af4285b09e06e30ce9979b6ad0

---

*[src/tools/antool/antool.py, line 313 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-Ktmi4G54NJOdFm1FNeG:-KtpFp4vajnFq3SsxNF5:bhducte) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/src/tools/antool/antool.py#L313)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

A comment added:
```
# subtract size of argc only, because 'data_size' does not include its own size
```
</blockquote></details>

This comment was added in another PR: https://github.com/pmem/pmemfile/pull/340 in the commit https://github.com/pmem/pmemfile/pull/340/commits/5242a2bb24822ff5436793c1507688a4c7569d51

---

*[src/tools/antool/antool.py, line 348 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-KtmjKx16atXP-qsRSQ4:-KtpG250HbHVwTFTcIoZ:bhducte) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/src/tools/antool/antool.py#L348)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

A comment added:
```
# subtract size of all read fields except of 'data_size' itself,
# because 'data_size' does not include its own size
```

</blockquote></details>

This comment was added in another PR: https://github.com/pmem/pmemfile/pull/340 in the commit https://github.com/pmem/pmemfile/pull/340/commits/5242a2bb24822ff5436793c1507688a4c7569d51

---

*[tests/antool/test-fi.sh, line 34 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/341#-Ktmp3zlUoxkKNKxEbsc:-KtpG7uosVBBGilp8AKH:b7ch2m6) ([raw file](https://github.com/pmem/pmemfile/blob/79a42bdcf93a9336fe15d2fa74f30b5bb961ea0e/tests/antool/test-fi.sh#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Just a mistake - it was the previous, old name. Fixed.
</blockquote></details>

File was moved to PR https://github.com/pmem/pmemfile/pull/347

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/341)*

**Comment by krzycz** [comment]
Reviewed 115 of 125 files at r1, 3 of 59 files at r2, 17 of 69 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/341)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/341#-:-KtqRJA4-pRAoBhAlbo-:bnfp4nl)*

**Pull request merged**
