### PR TITLE
antool: change name of a variable

### PR DESCRIPTION
**Pull request by ldorau**
Replace:
- ```syscall.unsupported``` with ```syscall.unsupported_type```
and:
- ```RESULT_UNSUPPORTED``` with ```RESULT_UNSUPPORTED_AT_ALL```

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/328)

### CODE REVIEW

**Comment by GBuella** [comment]
I might be too dumb for this, but it doesn't make it more clear to me.
What is this variable supposed to mean?
And why is a boolean assigned to it?

**Comment by krzycz** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/328)*

**Comment by ldorau** [comment]
This variable can take following values:
- RESULT_SUPPORTED = 0
- RESULT_UNSUPPORTED_YET = 1
- RESULT_UNSUPPORTED_RELATIVE = 2
- RESULT_UNSUPPORTED_FLAG = 3
- RESULT_UNSUPPORTED = 4

(the last one might be named RESULT_UNSUPPORTED_AT_ALL = 4)

What do you think - what could be the best name for it?
Marcin and I think that "unsupported_type" is better than the current one.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/328#-:-KtQQ4iy5IJA19ZdQWum:b-sru08d)*

**Comment by ldorau** [comment]
Description changed to:

Replace:
- ```syscall.unsupported``` with ```syscall.unsupported_type```
and:
- ```RESULT_UNSUPPORTED``` with ```RESULT_UNSUPPORTED_AT_ALL```

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/328)*

**Pull request merged**
