### PR TITLE
Implement timestamp management API

### PR DESCRIPTION
**Pull request by marcinslusarz**
Ref: #175

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/203)

### CODE REVIEW

**Comment by GBuella** [comment]
Reviewed 17 of 28 files at r1.
Review status: 17 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/203)*

**Comment by GBuella** [comment]
Review status: 17 of 28 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/libpmemfile-posix/timestamps.c, line 64 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4dWTVEeyOEGJBtUyU:-Kn4dWTW7e6m-fOs0IbF:b8c07oe) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/src/libpmemfile-posix/timestamps.c#L64)):*
> ```C
> 		tm = tm_buf;
> 	} else if (utm == UTIME_MACROS_ENABLED) {
> 		memcpy(tm_buf, tm, 2 * sizeof(*tm));
> ```

`memcpy(tm_buf, tm, sizeof(tm_buf));`

---

*[src/libpmemfile-posix/timestamps.c, line 72 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4clThWD2Ia4ulUMx9:-Kn4clThWD2Ia4ulUMxA:b-unhixi) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/src/libpmemfile-posix/timestamps.c#L72)):*
> ```C
> 			} else if (tm_buf[i].nsec == PMEMFILE_UTIME_OMIT) {
> 				/* nothing */
> 			} else if (tm_buf[i].nsec < 0 ||
> ```

It might look nicer to add a function for this, something like `static bool is_tm_valid(struct pmemfile_time t)`

---

*[src/libpmemfile-posix/timestamps.c, line 83 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4d2eh5q-dYydkCpwT:-Kn4d2eh5q-dYydkCpwU:b-7ropln) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/src/libpmemfile-posix/timestamps.c#L83)):*
> ```C
> 	} else {
> 		for (int i = 0; i < 2; ++i) {
> 			if (tm[i].nsec < 0 || tm[i].nsec > 999999999 ||
> ```

ditto

---

*[src/libpmemfile-posix/timestamps.c, line 235 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4dugl4dAY3jNxF3zr:-Kn4dugl4dAY3jNxF3zs:bcwmd0l) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/src/libpmemfile-posix/timestamps.c#L235)):*
> ```C
> 
> 	tm[0].sec = times[0].tv_sec;
> 	tm[0].nsec = times[0].tv_usec * 1000;
> ```

Might need to check for overflow here (or add a comment about one does not need to care about overflow).

---

*[src/libpmemfile-posix/timestamps.c, line 342 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4fCqbVwkb-o1dMvAI:-Kn4fCqbVwkb-o1dMvAJ:bgj6qf) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/src/libpmemfile-posix/timestamps.c#L342)):*
> ```C
> 		 * differently, but we have to emulate kernel behavior because
> 		 * futimens at glibc level is implemented using utimensat with
> 		 * NULL pathname. See "C library/ kernel ABI differences"
> ```

Well, I would say this does not need to be implemented here.
To me, it would look cleaner, if libpmemfile-posix followed the libc interface, and libpmemfile would take care of kernel interface, i.e.:
libpmemfile can translate `utimensat(fd, NULL, times, 0);` to `pmemfile_futimens(fd, times);`, and we could have this same comment in libpmemfile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/203)*

**Comment by GBuella** [comment]
Reviewed 11 of 28 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tests/posix/timestamps/timestamps.cpp, line 84 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4gyAKoAscY3AD4MYT:-Kn4gyALCsxn4TlYcmIZ:b-ljyne9) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/tests/posix/timestamps/timestamps.cpp#L84)):*
> ```cpp
> 		ASSERT_GT(st2.st_mtim.tv_nsec, st.st_mtim.tv_nsec);
> 
> 	tm.actime = -1;
> ```

Might wanna test the the edge cases of max values as well, with something like
```
tm.actime = std::numeric_limits<decltype(tm.actime)>::max();
tm.modtime = std::numeric_limits<decltype(tm.modtime)>::max();
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/203)*

**Comment by marcinslusarz** [comment]
Review status: 25 of 28 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/libpmemfile-posix/timestamps.c, line 64 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4dWTVEeyOEGJBtUyU:-Kn5FGH0i0Rs_P0DbTdU:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/src/libpmemfile-posix/timestamps.c#L64)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

`memcpy(tm_buf, tm, sizeof(tm_buf));`
</blockquote></details>

Done.

---

*[src/libpmemfile-posix/timestamps.c, line 72 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4clThWD2Ia4ulUMx9:-Kn5FFKBjdpA_MreKY8i:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/src/libpmemfile-posix/timestamps.c#L72)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

It might look nicer to add a function for this, something like `static bool is_tm_valid(struct pmemfile_time t)`
</blockquote></details>

Done.

---

*[src/libpmemfile-posix/timestamps.c, line 83 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4d2eh5q-dYydkCpwT:-Kn5FFlLuoSb_zC8Bw4R:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/src/libpmemfile-posix/timestamps.c#L83)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[src/libpmemfile-posix/timestamps.c, line 235 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4dugl4dAY3jNxF3zr:-Kn5HawrSYekyJELDOW1:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/src/libpmemfile-posix/timestamps.c#L235)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Might need to check for overflow here (or add a comment about one does not need to care about overflow).
</blockquote></details>

Done.

---

*[src/libpmemfile-posix/timestamps.c, line 342 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4fCqbVwkb-o1dMvAI:-Kn5Qu7mP8duJXyYQvaK:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/src/libpmemfile-posix/timestamps.c#L342)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Well, I would say this does not need to be implemented here.
To me, it would look cleaner, if libpmemfile-posix followed the libc interface, and libpmemfile would take care of kernel interface, i.e.:
libpmemfile can translate `utimensat(fd, NULL, times, 0);` to `pmemfile_futimens(fd, times);`, and we could have this same comment in libpmemfile.
</blockquote></details>

Done.

---

*[tests/posix/timestamps/timestamps.cpp, line 84 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4gyAKoAscY3AD4MYT:-Kn5RxBwrMQBd48RprBF:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/tests/posix/timestamps/timestamps.cpp#L84)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

Might wanna test the the edge cases of max values as well, with something like
```
tm.actime = std::numeric_limits<decltype(tm.actime)>::max();
tm.modtime = std::numeric_limits<decltype(tm.modtime)>::max();
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/203)*

**Comment by sarahjelinek** [comment]
Reviewed 25 of 28 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/203)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/203#-:-Kn5iTNLRYfQBFHVnbA5:bnfp4nl)*

**Comment by GBuella** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/posix/timestamps/timestamps.cpp, line 84 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4gyAKoAscY3AD4MYT:-Kn5tjvEmPb1ojjPm9VJ:b4zp05v) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/tests/posix/timestamps/timestamps.cpp#L84)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant it in a rather general sense:
Trying some very large numbers with timeval, utimbuf_t and whatnot

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/203)*

**Comment by marcinslusarz** [comment]
Review status: 27 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/posix/timestamps/timestamps.cpp, line 84 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/203#-Kn4gyAKoAscY3AD4MYT:-Kn9DO5tUW0Jtek1CBfW:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/d3d1c5715fd28ecc74ab8f11f9fa4320eda1ce45/tests/posix/timestamps/timestamps.cpp#L84)):*
<details><summary><i>Previously, GBuella (Gabor Buella) wrote…</i></summary><blockquote>

I meant it in a rather general sense:
Trying some very large numbers with timeval, utimbuf_t and whatnot
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/203)*

**Comment by GBuella** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/203#-:-Kn9JsAH4-rGVLtdDWVH:bnfp4nl)*

**Pull request merged**
