### PR TITLE
preload: pool locking optimization

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemfile/226)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/libpmemfile/preload.c, line 216 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne55KhUlfz3tZyJATK:-Kne55KhUlfz3tZyJATL:b-wuspl3) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L216)):*
> ```C
> 
> static int fd_ref[PMEMFILE_MAX_FD + 1];
> static pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
> ```

"mutex" as a global variable is too generic. Maybe "fd_table_mutex"?

---

*[src/libpmemfile/preload.c, line 219 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne5wybKNZ4QjmsQYa8:-Kne5wybKNZ4QjmsQYa9:b-g2a281) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L219)):*
> ```C
> 
> static void
> pmemfile_unref(long fd, struct fd_association *file)
> ```

This looks like pmemfile-posix function. Maybe rename it to fd_unref?

---

*[src/libpmemfile/preload.c, line 232 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne64rb9ql5PxHMOCqY:-Kne64rc0L5ZvI1sHy74:b-1y3mib) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L232)):*
> ```C
> 
> static struct fd_association
> pmemfile_ref(long fd)
> ```

... and fd_ref?

---

*[src/libpmemfile/preload.c, line 318 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne8U0uBP62DMhRi49l:-Kne8S8nCoEKH6ZWzl2j:b-rsws2k) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L318)):*
> ```C
> 	util_mutex_unlock(&mutex);
> 
> 	pmemfile_unref(fd, &file);
> ```

Hmm, this code doesn't seem to handle two simultaneous closes on one pmemfile file descriptor.

---

*[src/libpmemfile/preload.c, line 860 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne9XfHxqhZ9VKnDUSh:-Kne9XfHxqhZ9VKnDUSi:b3kqx) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L860)):*
> ```C
> 		long flags, long mode)
> {
> ```

.

---

*[src/libpmemfile/preload.c, line 1371 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-KneAJMAPtMmEq8fgknN:-KneAJMAPtMmEq8fgknO:b-62rr34) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L1371)):*
> ```C
> 			 */
> 			if (flags & ~AT_SYMLINK_NOFOLLOW)
> 				ret = -EINVAL;
> ```

This change looks wrong.

---

*[src/libpmemfile/preload.c, line 2110 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne4YLPC8od-QCLk5h5:-Kne4YLQcitK3q8L3Rv8:b1bmvif) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L2110)):*
> ```C
> 
> 	default:
> 			/* Did we miss something? */
> ```

too much indentation

---

*[src/libpmemfile/preload.c, line 2292 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne45wFsi_ABgUuj8ma:-Kne45wFsi_ABgUuj8mb:b-dlgycc) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L2292)):*
> ```C
> 
> 		if (!is_fda_null(&file))
> 			pmemfile_unref(arg0, &file);
> ```

You can do this inside of the first "if".

---

*[tests/preload/pool_locking/pool_locking.c, line 1 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne3_6QW1Dvy2q0hvXZ:-Kne3_6QW1Dvy2q0hvX_:b-4w3l4i) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/tests/preload/pool_locking/pool_locking.c#L1)):*
> ```C
> #include <stdlib.h>
> ```

Missing copyright and license.

---

*[tests/preload/pool_locking/pool_locking.c, line 11 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne3bb6AzBwMtwX3XSG:-Kne3bb6AzBwMtwX3XSH:b-y3va91) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/tests/preload/pool_locking/pool_locking.c#L11)):*
> ```C
> #include <sys/stat.h>
> 
> #define buffer_size 1024 * 1024
> ```

Please use capital letters for macros.

---

*[tests/preload/pool_locking/pool_locking.c, line 52 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne3Xi0DfXhqzHfDgoy:-Kne3Xi0DfXhqzHfDgoz:bq6t9lr) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/tests/preload/pool_locking/pool_locking.c#L52)):*
> ```C
> 		return 1;
> ```

Too many new lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226)*

**Comment by krzycz** [comment]
Reviewed 3 of 6 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226)*

**Comment by marcinslusarz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/libpmemfile/preload.c, line 1796 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/226#-KnisIyvlllLcgZ9GWNy:-KnisIyvlllLcgZ9GWNz:b3kqx) ([raw file](https://github.com/pmem/pmemfile/blob/a41c2cb2b1d6ec5bcbcde856d932f628d7b19831/src/libpmemfile/preload.c#L1796)):*
> ```C
> 			long arg4, long arg5)
> {
> ```

.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226#-:-KnitSZYMWne5opNkbxm:bnfp4nl)*

**Comment by igchor** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/libpmemfile/preload.c, line 216 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne55KhUlfz3tZyJATK:-Knn5ItE-_j1gtNdgbPf:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L216)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

"mutex" as a global variable is too generic. Maybe "fd_table_mutex"?
</blockquote></details>

Done.

---

*[src/libpmemfile/preload.c, line 219 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne5wybKNZ4QjmsQYa8:-Knn5MYukH2Y3qnnGIcM:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L219)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

This looks like pmemfile-posix function. Maybe rename it to fd_unref?
</blockquote></details>

Done.

---

*[src/libpmemfile/preload.c, line 232 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne64rb9ql5PxHMOCqY:-Knn5MvuHXxkQ0Ao3TQe:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L232)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

... and fd_ref?
</blockquote></details>

Done.

---

*[src/libpmemfile/preload.c, line 318 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne8U0uBP62DMhRi49l:-Knn5NNUjxFfSOypZdD7:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L318)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Hmm, this code doesn't seem to handle two simultaneous closes on one pmemfile file descriptor.
</blockquote></details>

Done.

---

*[src/libpmemfile/preload.c, line 860 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne9XfHxqhZ9VKnDUSh:-Knn5No41Jfr5N1wDp-A:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L860)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

---

*[src/libpmemfile/preload.c, line 1371 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-KneAJMAPtMmEq8fgknN:-Knn5OGi6-kV475ta8-q:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L1371)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

This change looks wrong.
</blockquote></details>

Done.

---

*[src/libpmemfile/preload.c, line 2110 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne4YLPC8od-QCLk5h5:-Knn5Oue-yH1CYlE-PxF:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L2110)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

too much indentation
</blockquote></details>

Done.

---

*[src/libpmemfile/preload.c, line 2292 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne45wFsi_ABgUuj8ma:-Knn5PFWNFx3hR_oDh3a:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/src/libpmemfile/preload.c#L2292)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

You can do this inside of the first "if".
</blockquote></details>

Done.

---

*[src/libpmemfile/preload.c, line 1796 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/226#-KnisIyvlllLcgZ9GWNy:-Knn5OWiFvwRtMdx4DcN:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/a41c2cb2b1d6ec5bcbcde856d932f628d7b19831/src/libpmemfile/preload.c#L1796)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

---

*[tests/preload/pool_locking/pool_locking.c, line 1 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne3_6QW1Dvy2q0hvXZ:-Knn5Pcj61PG__kkKdX7:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/tests/preload/pool_locking/pool_locking.c#L1)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Missing copyright and license.
</blockquote></details>

Done.

---

*[tests/preload/pool_locking/pool_locking.c, line 11 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne3bb6AzBwMtwX3XSG:-Knn5Py6awlGDGs6PJVx:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/tests/preload/pool_locking/pool_locking.c#L11)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please use capital letters for macros.
</blockquote></details>

Done.

---

*[tests/preload/pool_locking/pool_locking.c, line 52 at r1](https://reviewable.io:443/reviews/pmem/pmemfile/226#-Kne3Xi0DfXhqzHfDgoy:-Knn5QL40YNtr-C6nbyg:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/156e86256eaf31f98ee828f13507cb6fd705dcd4/tests/preload/pool_locking/pool_locking.c#L52)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Too many new lines.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226)*

**Comment by sarahjelinek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/libpmemfile/preload.c, line 263 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/226#-KnoRt-BvtCZhDctLFgA:-KnoRt-BvtCZhDctLFgB:b-wns5qt) ([raw file](https://github.com/pmem/pmemfile/blob/a41c2cb2b1d6ec5bcbcde856d932f628d7b19831/src/libpmemfile/preload.c#L263)):*
> ```C
> 
> static struct fd_desc
> fetch_fd(long fd)
> ```

I think the naming convention should be the same for all fd_XXX or XXX_fd functions. So, if we are going to follow fd_unref/fd_ref this should be named fd_fetch(). 

---

*[src/libpmemfile/preload.c, line 280 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/226#-KnoSAGYJDI1vWEkcbrU:-KnoSAGYJDI1vWEkcbrV:b-4u08wh) ([raw file](https://github.com/pmem/pmemfile/blob/a41c2cb2b1d6ec5bcbcde856d932f628d7b19831/src/libpmemfile/preload.c#L280)):*
> ```C
> 
> static void
> release_fd(struct fd_desc *at)
> ```

rename to fd_release()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226)*

**Comment by sarahjelinek** [comment]
What performance gain did you see from this?

**Comment by krzycz** [comment]
Reviewed 3 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226)*

**Comment by igchor** [comment]
About 5% in sqlite tests

---

Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/libpmemfile/preload.c, line 263 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/226#-KnoRt-BvtCZhDctLFgA:-Kns0vRk1cQdHcNmeum6:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/a41c2cb2b1d6ec5bcbcde856d932f628d7b19831/src/libpmemfile/preload.c#L263)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

I think the naming convention should be the same for all fd_XXX or XXX_fd functions. So, if we are going to follow fd_unref/fd_ref this should be named fd_fetch(). 
</blockquote></details>

Done.

---

*[src/libpmemfile/preload.c, line 280 at r2](https://reviewable.io:443/reviews/pmem/pmemfile/226#-KnoSAGYJDI1vWEkcbrU:-Kns0w7cC2oPIRe4lmAr:b-896fix) ([raw file](https://github.com/pmem/pmemfile/blob/a41c2cb2b1d6ec5bcbcde856d932f628d7b19831/src/libpmemfile/preload.c#L280)):*
<details><summary><i>Previously, sarahjelinek (Sarah Jelinek) wrote…</i></summary><blockquote>

rename to fd_release()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226#-:-Kns0y9ltSbdgFLuRXlW:bd85eeo)*

**Comment by marcinslusarz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226)*

**Comment by sarahjelinek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226#-:-KntjH61fy4TSOYro81C:bnfp4nl)*

**Comment by sarahjelinek** [comment]
Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmemfile/226)*

**Pull request merged**
